// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __qin_java_string_hash_code__, __qin_java_identity_hash_code__, __qin_java_value_hash_code__, __qin_java_values_equal__, __qin_java_hash_key__, __qin_java_hash_key_equals__ } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
class com_subhuti_error_ErrorPosition {
  __qin_field_tokenIndex: number | null = null as any;
  __qin_field_line: number | null = null as any;
  __qin_field_column: number | null = null as any;
  __qin_field_offset: number | null = null as any;
  __qin_field_sourceLine: string | null = null as any;
  __qin_field_ruleStackDepth: number | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 6: {
        const tokenIndex: any = __qin_args[0];
        const line: any = __qin_args[1];
        const column: any = __qin_args[2];
        const offset: any = __qin_args[3];
        const sourceLine: any = __qin_args[4];
        const ruleStackDepth: any = __qin_args[5];
        this.__qin_constructor_com_subhuti_error_ErrorPosition_6(tokenIndex, line, column, offset, sourceLine, ruleStackDepth);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: ErrorPosition/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_error_ErrorPosition_6(tokenIndex: number, line: number, column: number, offset: number, sourceLine: string, ruleStackDepth: number): void {
    this.__qin_field_tokenIndex = null;
    this.__qin_field_line = null;
    this.__qin_field_column = null;
    this.__qin_field_offset = null;
    this.__qin_field_sourceLine = null;
    this.__qin_field_ruleStackDepth = null;
    (() => {
      this.__qin_field_tokenIndex = tokenIndex;
      this.__qin_field_line = line;
      this.__qin_field_column = column;
      this.__qin_field_offset = offset;
      this.__qin_field_sourceLine = sourceLine;
      this.__qin_field_ruleStackDepth = ruleStackDepth;
      return null;
    })();
  }
  static of(tokenIndex: number, line: number, column: number): any {
    return new com_subhuti_error_ErrorPosition(tokenIndex, line, column, __qin_binary__("-", 0.0, 1.0), null, 0.0);
  }
  static full(tokenIndex: number, line: number, column: number, offset: number, sourceLine: string, ruleStackDepth: number): any {
    return new com_subhuti_error_ErrorPosition(tokenIndex, line, column, offset, sourceLine, ruleStackDepth);
  }
  format(): any {
    if (__qin_binary__("!=", this.__qin_field_sourceLine, null)) {
      return __QinJavaLangString.format("line %d, column %d (token #%d)", this.__qin_field_line, this.__qin_field_column, this.__qin_field_tokenIndex);
    }
    return __QinJavaLangString.format("line %d, column %d", this.__qin_field_line, this.__qin_field_column);
  }
  tokenIndex(): any {
    return this.__qin_field_tokenIndex;
  }
  line(): any {
    return this.__qin_field_line;
  }
  column(): any {
    return this.__qin_field_column;
  }
  offset(): any {
    return this.__qin_field_offset;
  }
  sourceLine(): any {
    return this.__qin_field_sourceLine;
  }
  ruleStackDepth(): any {
    return this.__qin_field_ruleStackDepth;
  }
  equals(other) {
    if (this === other) return true;
    if (!(other instanceof com_subhuti_error_ErrorPosition)) return false;
    return __qin_java_values_equal__(this.__qin_field_tokenIndex, other.__qin_field_tokenIndex)
      && __qin_java_values_equal__(this.__qin_field_line, other.__qin_field_line)
      && __qin_java_values_equal__(this.__qin_field_column, other.__qin_field_column)
      && __qin_java_values_equal__(this.__qin_field_offset, other.__qin_field_offset)
      && __qin_java_values_equal__(this.__qin_field_sourceLine, other.__qin_field_sourceLine)
      && __qin_java_values_equal__(this.__qin_field_ruleStackDepth, other.__qin_field_ruleStackDepth);
  }
  hashCode() {
    let result = 1;
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_tokenIndex);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_line);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_column);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_offset);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_sourceLine);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_ruleStackDepth);
    return result;
  }
  toString() {
    return "ErrorPosition[" + "tokenIndex=" + this.__qin_field_tokenIndex + ", " + "line=" + this.__qin_field_line + ", " + "column=" + this.__qin_field_column + ", " + "offset=" + this.__qin_field_offset + ", " + "sourceLine=" + this.__qin_field_sourceLine + ", " + "ruleStackDepth=" + this.__qin_field_ruleStackDepth + "]";
  }
}
const ErrorPosition = com_subhuti_error_ErrorPosition;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_subhuti_error_ErrorPosition };
