package com.qin.runtime.core.vue;

import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class QinVueSfcModuleAssembler {
    private static final Pattern COMPONENT_TAG_PATTERN = Pattern.compile(
            "<\\s*([A-Z][A-Za-z0-9_$]*)\\b");
    private static final Pattern CSSTS_ATOM_ENTRY_PATTERN = Pattern.compile("^\\s*([A-Za-z_$][\\w$]*)\\s*:");
    private static final Pattern CSSTS_MERGE_PATTERN = Pattern.compile("cssts\\.merge\\(([^)]*)\\)");
    private static final Pattern LOCAL_DECLARATION_PATTERN = Pattern.compile(
            "\\b(?:const|let|var|function)\\s+([A-Za-z_$][\\w$]*)");

    private QinVueSfcModuleAssembler() {
    }

    public static AssembledVueModule assemble(
            Path projectRoot,
            Path moduleFile,
            Map<String, Object> descriptor,
            String descriptorJson,
            QinVueModuleImportRewriter importRewriter) {
        String templateSource = QinVueTemplateBlockCompiler.compile(descriptor.get("template"));
        String vueRenderSource = QinVueTemplateBlockCompiler.compileVueRender(descriptor.get("template"));
        QinVueScriptBlockCompiler.CompiledScript script = QinVueScriptBlockCompiler.compile(
                projectRoot,
                moduleFile,
                descriptor.get("script"),
                descriptor.get("scriptSetup"),
                importRewriter);
        String styleSource = QinVueStyleBlockCompiler.compile(descriptor.get("styles"));
        String componentMounts = componentMounts(descriptor.get("template"));
        Set<String> atomNamesForPrelude = extractAtomNamesFromCode(script.code());
        atomNamesForPrelude.removeAll(extractLocalDeclarationNames(script.code()));
        Set<String> atomNamesForModule = extractAtomNames(script);
        String csstsPrelude = csstsPrelude(moduleFile, script, atomNamesForPrelude);
        String vueRuntimeImport = importRewriter == null ? "vue" : importRewriter.rewrite("vue");

        String moduleCode = """
                const __qin_vue_descriptor = %s;
                export const __qinVueDescriptor = __qin_vue_descriptor;
                import { h as __qinVueH } from '%s';
                %s
                %s
                %s
                %s
                %s
                function __qinMountVue(targetSelector = '#app') {
                  const target = typeof document !== 'undefined'
                    ? (typeof targetSelector === 'string'
                      ? (document.querySelector(targetSelector) || document.body)
                      : targetSelector)
                    : null;
                  if (!target) return null;
                  const html = __qinRenderVueTemplate();
                  target.innerHTML = html;
                  %s
                  return target;
                }
                if (typeof document !== 'undefined') {
                  __qinMountVue();
                }
                const __qin_vue_component = {
                  __qinVueDescriptor: __qin_vue_descriptor,
                  __qinMountVue,
                  render: __qinRenderVueComponent
                };
                export { __qinMountVue };
                export default __qin_vue_component;
                """.formatted(
                descriptorJson,
                vueRuntimeImport,
                csstsPrelude,
                styleSource.isBlank() ? "" : styleSource,
                script.code().isBlank() ? "" : script.code(),
                templateSource,
                vueRenderSource,
                componentMounts);
        return new AssembledVueModule(moduleCode, script.css(), ensureAtomModule(script.atomModule(), atomNamesForModule));
    }

    private static String ensureAtomModule(String atomModule, Set<String> atomNames) {
        if (atomNames == null || atomNames.isEmpty()) {
            return atomModule == null ? "" : atomModule;
        }
        boolean hasAll = atomModule != null;
        if (hasAll) {
            for (String atomName : atomNames) {
                if (!atomModule.contains(atomName + ":")) {
                    hasAll = false;
                    break;
                }
            }
        }
        if (hasAll) {
            return atomModule;
        }
        StringBuilder builder = new StringBuilder();
        builder.append("// Auto-generated by Qin from Vue lang=cssts").append(System.lineSeparator());
        builder.append("export const csstsAtom = {").append(System.lineSeparator());
        int index = 0;
        for (String atomName : atomNames) {
            builder.append("  ")
                    .append(atomName)
                    .append(": { '")
                    .append(camelToKebab(atomName))
                    .append("': null }");
            if (++index < atomNames.size()) {
                builder.append(',');
            }
            builder.append(System.lineSeparator());
        }
        builder.append("}").append(System.lineSeparator());
        builder.append("export default csstsAtom").append(System.lineSeparator());
        return builder.toString();
    }

    private static String camelToKebab(String text) {
        if (text == null || text.isBlank()) {
            return "";
        }
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char ch = text.charAt(i);
            if (Character.isUpperCase(ch) && i > 0) {
                builder.append('-');
            }
            builder.append(Character.toLowerCase(ch));
        }
        return builder.toString();
    }

    private static String csstsPrelude(
            Path moduleFile,
            QinVueScriptBlockCompiler.CompiledScript script,
            Set<String> atomNames) {
        if (script == null || script.atomModule() == null || script.atomModule().isBlank()) {
            return "";
        }
        String base = moduleFile.getFileName() == null
                ? ""
                : moduleFile.getFileName().toString();
        StringBuilder builder = new StringBuilder();
        builder.append("import * as __qinCsstsRuntime from './")
                .append(escapeImportPath(base))
                .append(".js?qin-vue-cssts=runtime';\n")
                .append("import { csstsAtom as __qinCsstsAtom } from './")
                .append(escapeImportPath(base))
                .append(".js?qin-vue-cssts=atom';\n");
        if (!atomNames.isEmpty()) {
            builder.append("const { ");
            int index = 0;
            for (String atomName : atomNames) {
                if (index++ > 0) {
                    builder.append(", ");
                }
                builder.append(atomName);
            }
            builder.append(" } = __qinCsstsAtom;\n");
        }
        return builder.toString();
    }

    private static Set<String> extractAtomNames(QinVueScriptBlockCompiler.CompiledScript script) {
        Set<String> names = new LinkedHashSet<>();
        if (script == null) {
            return names;
        }
        names.addAll(extractAtomNamesFromCode(script.code()));
        names.addAll(extractAtomNamesFromModule(script.atomModule()));
        return names;
    }

    private static Set<String> extractAtomNamesFromCode(String code) {
        Set<String> names = new LinkedHashSet<>();
        if (code == null || code.isBlank()) {
            return names;
        }
        Matcher matcher = CSSTS_MERGE_PATTERN.matcher(code);
        while (matcher.find()) {
            String[] parts = matcher.group(1).split(",");
            for (String part : parts) {
                String name = part.trim();
                if (name.matches("[A-Za-z_$][\\w$]*")) {
                    names.add(name);
                }
            }
        }
        return names;
    }

    private static Set<String> extractLocalDeclarationNames(String code) {
        Set<String> names = new LinkedHashSet<>();
        if (code == null || code.isBlank()) {
            return names;
        }
        Matcher matcher = LOCAL_DECLARATION_PATTERN.matcher(code);
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        return names;
    }

    private static Set<String> extractAtomNamesFromModule(String atomModule) {
        Set<String> names = new LinkedHashSet<>();
        if (atomModule == null || atomModule.isBlank()) {
            return names;
        }
        boolean inside = false;
        for (String line : atomModule.split("\\R")) {
            String trimmed = line.trim();
            if (!inside) {
                if (trimmed.startsWith("export const csstsAtom") && trimmed.contains("{")) {
                    inside = true;
                }
                continue;
            }
            if (trimmed.startsWith("}")) {
                break;
            }
            Matcher matcher = CSSTS_ATOM_ENTRY_PATTERN.matcher(line);
            if (matcher.find()) {
                names.add(matcher.group(1));
            }
        }
        return names;
    }

    private static String escapeImportPath(String text) {
        return text == null ? "" : text.replace("\\", "\\\\").replace("'", "\\'");
    }

    private static String componentMounts(Object templateBlock) {
        String template = QinVueSfcBlockSupport.extractBlockContent(templateBlock);
        Set<String> names = new LinkedHashSet<>();
        Matcher matcher = COMPONENT_TAG_PATTERN.matcher(template);
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        if (names.isEmpty()) {
            return "";
        }

        StringBuilder builder = new StringBuilder();
        for (String name : names) {
            builder.append("for (const __qinChildTarget of target.querySelectorAll('[data-qin-component=\"")
                    .append(name)
                    .append("\"]')) {\n")
                    .append("  const __qinChild = typeof ")
                    .append(name)
                    .append(" !== 'undefined' ? ")
                    .append(name)
                    .append(" : null;\n")
                    .append("  if (__qinChild && typeof __qinChild.__qinMountVue === 'function') {\n")
                    .append("    __qinChild.__qinMountVue(__qinChildTarget);\n")
                    .append("  }\n")
                    .append("}\n");
        }
        return builder.toString();
    }

    public record AssembledVueModule(
            String moduleCode,
            String csstsCss,
            String csstsAtomModule) {
    }
}
