// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __QinJavaLangThrowable, __QinJavaLangException, __QinJavaLangRuntimeException, __QinJavaLangReflectiveOperationException, __QinJavaLangClassNotFoundException, __QinJavaLangNoSuchMethodException, __QinJavaLangError, __QinJavaLangStackOverflowError, __QinJavaLangIllegalArgumentException, __QinJavaLangNumberFormatException, __QinJavaLangIllegalStateException, __QinJavaLangUnsupportedOperationException, __QinJavaIoIOException } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
const IllegalArgumentException = __QinJavaLangIllegalArgumentException;
class com_subhuti_parser_Alternative {
  __qin_field_supplier: any = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 1: {
        const supplier: any = __qin_args[0];
        this.__qin_constructor_com_subhuti_parser_Alternative_1(supplier);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: Alternative/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_parser_Alternative_1(supplier: any): void {
    this.__qin_field_supplier = null;
    this.__qin_field_supplier = supplier;
  }
  static of(supplier: any): any {
    supplier = __qin_java_functional(supplier);
    if (__qin_binary__("==", supplier, null)) {
      throw new __QinJavaLangIllegalArgumentException("supplier cannot be null");
    }
    return new com_subhuti_parser_Alternative(supplier);
  }
  execute(): any {
    return this.__qin_field_supplier.get();
  }
}
const Alternative = com_subhuti_parser_Alternative;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_subhuti_parser_Alternative };
