import { com_subhuti_struct_SubhutiMatchToken, com_subhuti_struct_SubhutiMatchToken$Builder } from "../struct/SubhutiMatchToken.ts";
const SubhutiMatchToken = com_subhuti_struct_SubhutiMatchToken;

// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __QinJavaUtilArrayList, __QinJavaUtilUnmodifiableList } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
class com_subhuti_parser_ParseRecordNode {
  __qin_field_name: string | null = null as any;
  __qin_field_children: any = null as any;
  __qin_field_startTokenIndex: number | null = null as any;
  __qin_field_endTokenIndex: number | null = null as any;
  __qin_field_token: com_subhuti_struct_SubhutiMatchToken | null = null as any;
  __qin_field_value: string | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 0: {
        this.__qin_constructor_com_subhuti_parser_ParseRecordNode_0();
        return;
      }
      case 1: {
        const name: any = __qin_args[0];
        this.__qin_constructor_com_subhuti_parser_ParseRecordNode_1(name);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: ParseRecordNode/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_parser_ParseRecordNode_0(): void {
    this.__qin_field_name = null;
    this.__qin_field_children = null;
    this.__qin_field_startTokenIndex = null;
    this.__qin_field_endTokenIndex = null;
    this.__qin_field_token = null;
    this.__qin_field_value = null;
    this.__qin_field_children = new __QinJavaUtilArrayList();
  }
  __qin_constructor_com_subhuti_parser_ParseRecordNode_1(name: string): void {
    this.__qin_field_name = null;
    this.__qin_field_children = null;
    this.__qin_field_startTokenIndex = null;
    this.__qin_field_endTokenIndex = null;
    this.__qin_field_token = null;
    this.__qin_field_value = null;
    this.__qin_field_name = name;
    this.__qin_field_children = new __QinJavaUtilArrayList();
  }
  getName(): any {
    return this.__qin_field_name;
  }
  setName(name: string): any {
    this.__qin_field_name = name;
    return null;
  }
  getChildren(): any {
    return this.__qin_field_children;
  }
  setChildren(children: any): any {
    this.__qin_field_children = children;
    return null;
  }
  getStartTokenIndex(): any {
    return this.__qin_field_startTokenIndex;
  }
  setStartTokenIndex(startTokenIndex: number): any {
    this.__qin_field_startTokenIndex = startTokenIndex;
    return null;
  }
  getEndTokenIndex(): any {
    return this.__qin_field_endTokenIndex;
  }
  setEndTokenIndex(endTokenIndex: number): any {
    this.__qin_field_endTokenIndex = endTokenIndex;
    return null;
  }
  getToken(): any {
    return this.__qin_field_token;
  }
  setToken(token: com_subhuti_struct_SubhutiMatchToken): any {
    this.__qin_field_token = token;
    return null;
  }
  getValue(): any {
    return this.__qin_field_value;
  }
  setValue(value: string): any {
    this.__qin_field_value = value;
    return null;
  }
}
const ParseRecordNode = com_subhuti_parser_ParseRecordNode;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_subhuti_parser_ParseRecordNode };
