import { com_subhuti_lookahead_SubhutiTokenConsumer } from "../lookahead/SubhutiTokenConsumer.ts";
import { com_subhuti_struct_SubhutiCreateToken, com_subhuti_struct_SubhutiCreateToken$Builder } from "../struct/SubhutiCreateToken.ts";
import { com_subhuti_parser_SubhutiParserFinal } from "./SubhutiParserFinal.ts";
import { com_subhuti_parser_SubhutiParserCombinators, com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher, com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext, com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext, com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame } from "./SubhutiParserCombinators.ts";
import { com_subhuti_parser_SubhutiParserCore, com_subhuti_parser_SubhutiParserCore$RuleExecutionResult } from "./SubhutiParserCore.ts";
import { com_subhuti_parser_SubhutiParserState } from "./SubhutiParserState.ts";
import { com_subhuti_lookahead_SubhutiTokenLookahead } from "../lookahead/SubhutiTokenLookahead.ts";
const SubhutiTokenConsumer = com_subhuti_lookahead_SubhutiTokenConsumer;
const SubhutiCreateToken = com_subhuti_struct_SubhutiCreateToken;
const SubhutiParserFinal = com_subhuti_parser_SubhutiParserFinal;
const SubhutiParserCombinators = com_subhuti_parser_SubhutiParserCombinators;
const StopTokenMatcher = com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher;
const AllowErrorOrBranchContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext;
const AllowErrorContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext;
const ManyTolerantFrame = com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame;
const SubhutiParserCore = com_subhuti_parser_SubhutiParserCore;
const RuleExecutionResult = com_subhuti_parser_SubhutiParserCore$RuleExecutionResult;
const SubhutiParserState = com_subhuti_parser_SubhutiParserState;

// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __QinSlf4jLogger, __QinSlf4jLoggerFactory, __QinJavaLangThrowable, __QinJavaLangException, __QinJavaLangRuntimeException, __QinJavaLangReflectiveOperationException, __QinJavaLangClassNotFoundException, __QinJavaLangNoSuchMethodException, __QinJavaLangError, __QinJavaLangStackOverflowError, __QinJavaLangIllegalArgumentException, __QinJavaLangNumberFormatException, __QinJavaLangIllegalStateException, __QinJavaLangUnsupportedOperationException, __QinJavaIoIOException } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
const LoggerFactory = __QinSlf4jLoggerFactory;
const ClassNotFoundException = __QinJavaLangClassNotFoundException;
const RuntimeException = __QinJavaLangRuntimeException;
const Exception = __QinJavaLangException;
class com_subhuti_parser_SubhutiParser extends com_subhuti_parser_SubhutiParserFinal {
  static __qin_field_log: any = null as any;
  static __qin_field_cachedCreateMethod: any = null as any;
  static __qin_field_factoryInitialized: boolean | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 3: {
        const sourceCode: any = __qin_args[0];
        const tokenConsumerClass: any = __qin_args[1];
        const tokens: any = __qin_args[2];
        super(sourceCode, tokenConsumerClass, tokens);
        this.__qin_constructor_com_subhuti_parser_SubhutiParser_3(sourceCode, tokenConsumerClass, tokens);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SubhutiParser/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_parser_SubhutiParser_3(sourceCode: string, tokenConsumerClass: any, tokens: any): void {
    null;
  }
  static create(parserClass: any, ...args: any[]): any {
    throw new __QinJavaLangUnsupportedOperationException(
      "SubhutiParser.create(...) was the removed runtime enhancement entry. "
        + "Instantiate the grammar's generated/static enhanced parser class instead of "
        + parserClass
        + "."
    );
  }
}
const SubhutiParser = com_subhuti_parser_SubhutiParser;
com_subhuti_parser_SubhutiParser.__qin_field_log = __QinSlf4jLoggerFactory.getLogger(({ getName() { return "com.subhuti.parser.SubhutiParser"; }, getSimpleName() { return "SubhutiParser"; }, getDeclaredConstructor(...__qin_types) { const __qin_ctor = com_subhuti_parser_SubhutiParser; return { newInstance(...__qin_args) { return new __qin_ctor(...__qin_args); } }; }, getConstructor(...__qin_types) { return this.getDeclaredConstructor(...__qin_types); }, equals(other) { return other != null && typeof other.getName === "function" && other.getName() === "com.subhuti.parser.SubhutiParser"; }, hashCode() { return 1130041035; }, toString() { return "class com.subhuti.parser.SubhutiParser"; } }));
com_subhuti_parser_SubhutiParser.__qin_field_cachedCreateMethod = null;
com_subhuti_parser_SubhutiParser.__qin_field_factoryInitialized = false;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_subhuti_parser_SubhutiParser };
