import { com_subhuti_struct_SubhutiCst, com_subhuti_struct_SubhutiCst$Builder } from "../struct/SubhutiCst.ts";
const SubhutiCst = com_subhuti_struct_SubhutiCst;

// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __QinJavaLangInteger, __QinJavaLangStringBuilder, __QinJavaUtilArrayList, __QinJavaUtilUnmodifiableList, __QinJavaUtilHashMap, __QinJavaUtilUnmodifiableMap } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
const ArrayList = __QinJavaUtilArrayList;
const Integer = __QinJavaLangInteger;
const StringBuilder = __QinJavaLangStringBuilder;
const LinkedHashMap = __QinJavaUtilHashMap;
class com_subhuti_debug_SubhutiDebugUtils {
  constructor(...__qin_args: any[]) {
    if (__qin_args.length !== 0) {
      throw new Error("Unsupported Java constructor arity: SubhutiDebugUtils/" + __qin_args.length);
    }
  }
  static collectTokens(node: com_subhuti_struct_SubhutiCst): any {
    let values: any = new __QinJavaUtilArrayList();
    if (__qin_binary__("==", node, null)) {
      return values;
    }
    if ((() => {
      if (__qin_binary__("!=", node.getValue(), null)) {
        return (() => {
      if (__qin_binary__("==", node.getChildren(), null)) {
        return true;
      }
      return __QinJavaLangString.isEmpty(node.getChildren());
    })();
      }
      return false;
    })()) {
      values.add(node.getValue());
    }
    if (__qin_binary__("!=", node.getChildren(), null)) {
      for (const child of node.getChildren()) {
        values.addAll(com_subhuti_debug_SubhutiDebugUtils.collectTokens(child));
      }
    }
    return values;
  }
  static validateTokenCompleteness(cst: com_subhuti_struct_SubhutiCst, inputTokens: any): any {
    let cstTokens: any = com_subhuti_debug_SubhutiDebugUtils.collectTokens(cst);
    let missing: any = new __QinJavaUtilArrayList();
    for (let i: any = 0.0; __qin_binary__("<", i, inputTokens.size()); i = __qin_binary__("+", i, 1.0)) {
      if ((() => {
      if (__qin_binary__(">=", i, cstTokens.size())) {
        return true;
      }
      return (() => {
      if (__QinJavaLangString.equals(inputTokens.get(i), cstTokens.get(i))) {
        return false;
      }
      return true;
    })();
    })()) {
        missing.add(inputTokens.get(i));
      }
    }
    let complete: any = (() => {
      if (__QinJavaLangString.isEmpty(missing)) {
        return __qin_binary__("==", inputTokens.size(), cstTokens.size());
      }
      return false;
    })();
    return new com_subhuti_debug_SubhutiDebugUtils$TokenValidationResult(complete, inputTokens.size(), cstTokens.size(), inputTokens, cstTokens, missing);
  }
  static validateStructure(...__qin_args: any[]): any {
    if (__qin_args.length === 2 && (__qin_args[0] === null || __qin_args[0] instanceof com_subhuti_struct_SubhutiCst) && (__qin_args[1] === null || typeof __qin_args[1] === "string")) return this.__qin_overload_validateStructure_2_0(...__qin_args);
    if (__qin_args.length === 1 && (__qin_args[0] === null || __qin_args[0] instanceof com_subhuti_struct_SubhutiCst)) return this.__qin_overload_validateStructure_1_1(...__qin_args);
    throw new Error("Unsupported Java overload: validateStructure/" + __qin_args.length);
  }
  static __qin_overload_validateStructure_2_0(node: com_subhuti_struct_SubhutiCst, path: string): any {
    if (__qin_binary__("==", path, null)) {
      path = "root";
    }
    let errors: any = new __QinJavaUtilArrayList();
    if (__qin_binary__("==", node, null)) {
      errors.add(new com_subhuti_debug_SubhutiDebugUtils$StructureError(path, "Node is null"));
      return errors;
    }
    if ((() => {
      if (__qin_binary__("==", node.getName(), null)) {
        return __qin_binary__("==", node.getValue(), null);
      }
      return false;
    })()) {
      errors.add(new com_subhuti_debug_SubhutiDebugUtils$StructureError(path, "Node has neither name nor value"));
    }
    if (__qin_binary__("!=", node.getChildren(), null)) {
      for (let i: any = 0.0; __qin_binary__("<", i, node.getChildren().size()); i = __qin_binary__("+", i, 1.0)) {
        let child: any = node.getChildren().get(i);
        let childPath: any = __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", path, ".children["), i), "]");
        if (__qin_binary__("==", child, null)) {
          errors.add(new com_subhuti_debug_SubhutiDebugUtils$StructureError(childPath, "Child is null"));
          continue;
        }
        errors.addAll(com_subhuti_debug_SubhutiDebugUtils.validateStructure(child, childPath));
      }
    }
    if ((() => {
      if ((() => {
      if (__qin_binary__("!=", node.getValue(), null)) {
        return __qin_binary__("!=", node.getChildren(), null);
      }
      return false;
    })()) {
        return (() => {
      if (__QinJavaLangString.isEmpty(node.getChildren())) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })()) {
      errors.add(new com_subhuti_debug_SubhutiDebugUtils$StructureError(path, "Leaf node has both value and non-empty children"));
    }
    return errors;
  }
  static __qin_overload_validateStructure_1_1(node: com_subhuti_struct_SubhutiCst): any {
    return com_subhuti_debug_SubhutiDebugUtils.validateStructure(node, "root");
  }
  static getCstStatistics(node: com_subhuti_struct_SubhutiCst): any {
    let stats: any = new com_subhuti_debug_SubhutiDebugUtils$CstStatistics();
    com_subhuti_debug_SubhutiDebugUtils.traverseForStats(node, 0.0, stats);
    return stats;
  }
  static traverseForStats(node: com_subhuti_struct_SubhutiCst, depth: number, stats: com_subhuti_debug_SubhutiDebugUtils$CstStatistics): any {
    if (__qin_binary__("==", node, null)) {
      return null;
    }
    stats.__qin_field_totalNodes = __qin_binary__("+", stats.__qin_field_totalNodes, 1.0);
    stats.__qin_field_maxDepth = Math.max(stats.__qin_field_maxDepth, depth);
    if (__qin_binary__("!=", node.getName(), null)) {
      stats.__qin_field_nodeTypes.merge(node.getName(), 1.0, __QinJavaLangInteger.sum.bind(__QinJavaLangInteger));
    }
    if ((() => {
      if (__qin_binary__("==", node.getChildren(), null)) {
        return true;
      }
      return __QinJavaLangString.isEmpty(node.getChildren());
    })()) {
      stats.__qin_field_leafNodes = __qin_binary__("+", stats.__qin_field_leafNodes, 1.0);
    } else {
      for (const child of node.getChildren()) {
        com_subhuti_debug_SubhutiDebugUtils.traverseForStats(child, __qin_binary__("+", depth, 1.0), stats);
      }
    }
    return null;
  }
  static formatCst(...__qin_args: any[]): any {
    if (__qin_args.length === 1 && (__qin_args[0] === null || __qin_args[0] instanceof com_subhuti_struct_SubhutiCst)) return this.__qin_overload_formatCst_1_0(...__qin_args);
    if (__qin_args.length === 3 && (__qin_args[0] === null || __qin_args[0] instanceof com_subhuti_struct_SubhutiCst) && (__qin_args[1] === null || typeof __qin_args[1] === "string") && typeof __qin_args[2] === "boolean") return this.__qin_overload_formatCst_3_1(...__qin_args);
    throw new Error("Unsupported Java overload: formatCst/" + __qin_args.length);
  }
  static __qin_overload_formatCst_1_0(cst: com_subhuti_struct_SubhutiCst): any {
    return com_subhuti_debug_SubhutiDebugUtils.formatCst(cst, "", true);
  }
  static __qin_overload_formatCst_3_1(cst: com_subhuti_struct_SubhutiCst, prefix: string, isLast: boolean): any {
    if (__qin_binary__("==", cst, null)) {
      return "";
    }
    let sb: any = new __QinJavaLangStringBuilder();
    let connector: any = (() => {
      if (isLast) {
        return "└─";
      }
      return "├─";
    })();
    sb.append(com_subhuti_debug_SubhutiDebugUtils.formatNode(cst, prefix, connector)).append("\n");
    if ((() => {
      if (__qin_binary__("!=", cst.getChildren(), null)) {
        return (() => {
      if (__QinJavaLangString.isEmpty(cst.getChildren())) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })()) {
      let childPrefix: any = __qin_binary__("+", prefix, (() => {
      if (isLast) {
        return "   ";
      }
      return "│  ";
    })());
      for (let i: any = 0.0; __qin_binary__("<", i, cst.getChildren().size()); i = __qin_binary__("+", i, 1.0)) {
        let isLastChild: any = __qin_binary__("==", i, __qin_binary__("-", cst.getChildren().size(), 1.0));
        sb.append(com_subhuti_debug_SubhutiDebugUtils.formatCst(cst.getChildren().get(i), childPrefix, isLastChild));
      }
    }
    return sb.toString();
  }
  static formatNode(cst: com_subhuti_struct_SubhutiCst, prefix: string, connector: string): any {
    let isToken: any = __qin_binary__("!=", cst.getValue(), null);
    if (isToken) {
      let value: any = com_subhuti_debug_SubhutiDebugUtils.formatTokenValue(cst.getValue());
      let location: any = (() => {
      if (__qin_binary__("!=", cst.getLocation(), null)) {
        return com_subhuti_debug_SubhutiDebugUtils.formatLocation(cst.getLocation());
      }
      return "";
    })();
      return __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", prefix, connector), cst.getName()), ": \""), value), "\" "), location);
    } else {
      return __qin_binary__("+", __qin_binary__("+", prefix, connector), cst.getName());
    }
    return null;
  }
  static formatTokenValue(value: string): any {
    if (__qin_binary__("==", value, null)) {
      return "";
    }
    return value.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
  }
  static formatLocation(loc: any): any {
    if (__qin_binary__("==", loc, null)) {
      return "";
    }
    return loc.toString();
  }
}
const SubhutiDebugUtils = com_subhuti_debug_SubhutiDebugUtils;
class com_subhuti_debug_SubhutiDebugUtils$TokenValidationResult {
  __qin_field_complete: boolean | null = null as any;
  __qin_field_inputCount: number | null = null as any;
  __qin_field_cstCount: number | null = null as any;
  __qin_field_inputTokens: any = null as any;
  __qin_field_cstTokens: any = null as any;
  __qin_field_missing: any = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 6: {
        const complete: any = __qin_args[0];
        const inputCount: any = __qin_args[1];
        const cstCount: any = __qin_args[2];
        const inputTokens: any = __qin_args[3];
        const cstTokens: any = __qin_args[4];
        const missing: any = __qin_args[5];
        this.__qin_constructor_com_subhuti_debug_SubhutiDebugUtils$TokenValidationResult_6(complete, inputCount, cstCount, inputTokens, cstTokens, missing);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SubhutiDebugUtils$TokenValidationResult/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_debug_SubhutiDebugUtils$TokenValidationResult_6(complete: boolean, inputCount: number, cstCount: number, inputTokens: any, cstTokens: any, missing: any): void {
    this.__qin_field_complete = null;
    this.__qin_field_inputCount = null;
    this.__qin_field_cstCount = null;
    this.__qin_field_inputTokens = null;
    this.__qin_field_cstTokens = null;
    this.__qin_field_missing = null;
    this.__qin_field_complete = complete;
    this.__qin_field_inputCount = inputCount;
    this.__qin_field_cstCount = cstCount;
    this.__qin_field_inputTokens = inputTokens;
    this.__qin_field_cstTokens = cstTokens;
    this.__qin_field_missing = missing;
  }
  toString(): any {
    if (this.__qin_field_complete) {
      return __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", "✅ Token 完整 (", this.__qin_field_cstCount), "/"), this.__qin_field_inputCount), ")");
    } else {
      return __qin_binary__("+", "❌ Token 不完整，缺失: ", this.__qin_field_missing);
    }
    return null;
  }
}
const SubhutiDebugUtils$TokenValidationResult = com_subhuti_debug_SubhutiDebugUtils$TokenValidationResult;
class com_subhuti_debug_SubhutiDebugUtils$StructureError {
  __qin_field_path: string | null = null as any;
  __qin_field_issue: string | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 2: {
        const path: any = __qin_args[0];
        const issue: any = __qin_args[1];
        this.__qin_constructor_com_subhuti_debug_SubhutiDebugUtils$StructureError_2(path, issue);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SubhutiDebugUtils$StructureError/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_debug_SubhutiDebugUtils$StructureError_2(path: string, issue: string): void {
    this.__qin_field_path = null;
    this.__qin_field_issue = null;
    this.__qin_field_path = path;
    this.__qin_field_issue = issue;
  }
  toString(): any {
    return __qin_binary__("+", __qin_binary__("+", this.__qin_field_path, ": "), this.__qin_field_issue);
  }
}
const SubhutiDebugUtils$StructureError = com_subhuti_debug_SubhutiDebugUtils$StructureError;
class com_subhuti_debug_SubhutiDebugUtils$CstStatistics {
  __qin_field_totalNodes: number | null = null as any;
  __qin_field_leafNodes: number | null = null as any;
  __qin_field_maxDepth: number | null = null as any;
  __qin_field_nodeTypes: any = null as any;
  constructor(...__qin_args: any[]) {
    if (__qin_args.length !== 0) {
      throw new Error("Unsupported Java constructor arity: SubhutiDebugUtils$CstStatistics/" + __qin_args.length);
    }
    this.__qin_field_totalNodes = 0.0;
    this.__qin_field_leafNodes = 0.0;
    this.__qin_field_maxDepth = 0.0;
    this.__qin_field_nodeTypes = new __QinJavaUtilHashMap();
  }
  toString(): any {
    let sb: any = new __QinJavaLangStringBuilder();
    sb.append("总节点数: ").append(this.__qin_field_totalNodes).append("\n");
    sb.append("叶子节点: ").append(this.__qin_field_leafNodes).append("\n");
    sb.append("最大深度: ").append(this.__qin_field_maxDepth).append("\n");
    sb.append("节点类型: ").append(this.__qin_field_nodeTypes.size()).append(" 种\n");
    sb.append("类型分布:\n");
    this.__qin_field_nodeTypes.forEach(__qin_java_functional((name, count) => {
      return sb.append("  ").append(name).append(": ").append(count).append("\n");
    }));
    return sb.toString();
  }
}
const SubhutiDebugUtils$CstStatistics = com_subhuti_debug_SubhutiDebugUtils$CstStatistics;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_subhuti_debug_SubhutiDebugUtils, com_subhuti_debug_SubhutiDebugUtils$TokenValidationResult, com_subhuti_debug_SubhutiDebugUtils$StructureError, com_subhuti_debug_SubhutiDebugUtils$CstStatistics };
