package com.qin.runtime.core;

import java.nio.file.Path;
import java.util.List;

public final class QinJavaProjectSlimeParserTsBundleSmokeTestMain {
    private QinJavaProjectSlimeParserTsBundleSmokeTestMain() {
    }

    public static void main(String[] args) throws Exception {
        Path qinRoot = Path.of("").toAbsolutePath();
        Path workspaceRoot = qinRoot.getParent();
        List<Path> sourceRoots = List.of(
                workspaceRoot.resolve("slime").resolve("java-slime").resolve("slime-parser")
                        .resolve("src").resolve("main").resolve("java"),
                workspaceRoot.resolve("slime").resolve("java-slime").resolve("slime-token")
                        .resolve("src").resolve("main").resolve("java"),
                workspaceRoot.resolve("slime").resolve("java-slime").resolve("subhuti-java")
                        .resolve("src").resolve("main").resolve("java"));

        Path outputFile = qinRoot.resolve(".qin")
                .resolve("generated")
                .resolve("slime-parser")
                .resolve("slime-parser.bundle.ts");
        String generated = new QinJavaProjectJsCompiler()
                .compileSuperclassClosureTs(sourceRoots, "com.slime.parser.SlimeParser", outputFile);

        require(outputFile.getFileName().toString().endsWith(".ts"), "TS bundle output extension");
        require(generated.contains("// Generated by Qin TypeScript backend"), "TS backend banner");
        require(generated.contains("class com_slime_parser_SlimeParser extends com_slime_parser_typescript_SlimeTSDeclarationParser"),
                "generated SlimeParser TS class");
        require(generated.contains("constructor(...__qin_args: any[])"),
                "generated constructor type annotation");
        require(generated.contains("__qin_subhuti_rule_cache_key([params])"),
                "Subhuti rule cache key uses explicit TS parameter array");
        require(!generated.contains("__qin_subhuti_rule_cache_key(arguments)"),
                "Subhuti rule cache key avoids runtime arguments object");
        require(generated.contains("__qin_targetFun.call(this, ...__qin_ruleArgs)"),
                "Subhuti TS runtime accepts external decorator rule args");
        require(generated.contains("__qin_args[3] === null || typeof __qin_args[3] === \"string\""),
                "Subhuti cacheKey overload keeps string guard");
        require(generated.contains("typeof __qin_arg.alt === \"function\""),
                "Subhuti Alternative varargs guard accepts local TS Alternative.alt");
        require(generated.contains("typeof __qin_arg.run === \"function\""),
                "Subhuti Alternative varargs guard accepts local TS Alternative.run");
        require(generated.contains("const __qinGlobal = globalThis as any;"),
                "generated TS-safe global export bridge");

        System.out.println("Generated TS bundle: " + outputFile);
        System.out.println("QinJavaProjectSlimeParserTsBundleSmokeTestMain OK");
    }

    private static void require(boolean condition, String label) {
        if (!condition) {
            throw new IllegalStateException("Expected " + label);
        }
    }
}
