package com.qin.lang.frontend.adapter;

import com.qin.lang.ir.QinIrBuiltinCallExpression;
import com.qin.lang.ir.QinIrClassDeclaration;
import com.qin.lang.ir.QinIrMethodDeclaration;
import com.qin.lang.ir.QinIrProgram;

/**
 * Smoke test for static zero-argument arrow IIFEs generated by Java-to-TS block expressions.
 */
public final class QinDeclarationIrStaticIifeSmokeTestMain {
    private QinDeclarationIrStaticIifeSmokeTestMain() {
    }

    public static void main(String[] args) {
        String source = """
                class Probe {
                  include(tokenName: any, excludeNames: any) {
                    return (() => {
                      if (__qin_binary__("!=", tokenName, null)) {
                        return (() => {
                          if (excludeNames.contains(tokenName)) {
                            return false
                          }
                          return true
                        })()
                      }
                      return false
                    })()
                  }
                }
                """;

        QinIrProgram program = new QinFrontendLowerer().lowerSource(source);
        QinIrClassDeclaration declaration = program.classDeclarations().stream()
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("Missing class declaration"));
        QinIrMethodDeclaration include = declaration.methods().stream()
                .filter(candidate -> "include".equals(candidate.name()))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("Missing include method"));
        if (!(include.returnExpression() instanceof QinIrBuiltinCallExpression outer)
                || !"__qin_conditional__".equals(outer.methodName())) {
            throw new IllegalStateException("Expected outer static IIFE to lower to conditional builtin, got "
                    + include.returnExpression());
        }
        if (!(outer.arguments().get(1) instanceof QinIrBuiltinCallExpression inner)
                || !"__qin_conditional__".equals(inner.methodName())) {
            throw new IllegalStateException("Expected nested static IIFE to lower to conditional builtin, got "
                    + outer.arguments().get(1));
        }

        System.out.println("QinDeclarationIrStaticIifeSmokeTestMain passed.");
    }
}
