package com.qin.lang.backend.js;

import com.qin.lang.ir.QinIrBuiltinCallExpression;
import com.qin.lang.ir.QinIrBooleanLiteral;
import com.qin.lang.ir.QinIrConstDeclaration;
import com.qin.lang.ir.QinIrConsoleLogJavaInstanceCall;
import com.qin.lang.ir.QinIrConsoleLogJavaStaticCall;
import com.qin.lang.ir.QinIrConsoleLogStatement;
import com.qin.lang.ir.QinIrConsoleLogValue;
import com.qin.lang.ir.QinIrExpression;
import com.qin.lang.ir.QinIrIdentifierReference;
import com.qin.lang.ir.QinIrJavaImport;
import com.qin.lang.ir.QinIrJavaInstanceMethodCall;
import com.qin.lang.ir.QinIrJsImport;
import com.qin.lang.ir.QinIrJavaNewExpression;
import com.qin.lang.ir.QinIrMemberAccessExpression;
import com.qin.lang.ir.QinIrNullLiteral;
import com.qin.lang.ir.QinIrNumberLiteral;
import com.qin.lang.ir.QinIrObjectLiteral;
import com.qin.lang.ir.QinIrObjectProperty;
import com.qin.lang.ir.QinIrProgram;
import com.qin.lang.ir.QinIrStringLiteral;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Minimal JavaScript backend for Qin IR.
 */
public final class QinJsBackend {
    public String compileProgram(QinIrProgram program) {
        Objects.requireNonNull(program, "program cannot be null");

        StringBuilder js = new StringBuilder();
        js.append("// Generated by Qin JS backend\n");
        emitJavaAliases(js, program.javaImports());
        emitJsImports(js, program.jsImports());
        ensureNoUnsupportedJavaInterop(program);

        Map<String, QinIrExpression> declarationMap = new LinkedHashMap<>();
        for (QinIrConstDeclaration declaration : program.declarations()) {
            js.append("const ").append(declaration.name()).append(" = ");
            emitExpression(js, declaration.initializer());
            js.append(";\n");
            declarationMap.put(declaration.name(), declaration.initializer());
        }
        if (!declarationMap.isEmpty()) {
            js.append("\n");
        }

        js.append("function run() {\n");
        emitConsoleValueLogs(js, program.consoleValueLogs());
        emitConsoleLogs(js, declarationMap, program.consoleLogs());
        emitJavaStaticConsoleLogs(js, program.javaStaticConsoleLogs());
        String returnName = lastDeclarationName(program.declarations());
        if (returnName != null) {
            js.append("  return ").append(returnName).append(";\n");
        } else {
            js.append("  return null;\n");
        }
        js.append("}\n\n");
        js.append("const __qinResult = run();\n");
        js.append("if (typeof globalThis !== 'undefined') {\n");
        js.append("  globalThis.__qinResult = __qinResult;\n");
        js.append("}\n");

        return js.toString();
    }

    private void emitJavaAliases(StringBuilder js, List<QinIrJavaImport> javaImports) {
        for (QinIrJavaImport javaImport : javaImports) {
            if ("java.lang.Math".equals(javaImport.ownerBinaryName())) {
                if (!"Math".equals(javaImport.localName())) {
                    js.append("const ").append(javaImport.localName()).append(" = Math;\n");
                }
                continue;
            }
            throw new IllegalArgumentException(
                    "JS backend only supports java.lang.Math interop aliasing, got: " + javaImport.ownerBinaryName());
        }
        if (!javaImports.isEmpty()) {
            js.append("\n");
        }
    }

    private void emitJsImports(StringBuilder js, List<QinIrJsImport> jsImports) {
        if (jsImports == null || jsImports.isEmpty()) {
            return;
        }

        Map<String, List<QinIrJsImport>> grouped = new LinkedHashMap<>();
        for (QinIrJsImport jsImport : jsImports) {
            grouped.computeIfAbsent(jsImport.moduleName(), ignored -> new java.util.ArrayList<>())
                    .add(jsImport);
        }

        for (Map.Entry<String, List<QinIrJsImport>> entry : grouped.entrySet()) {
            List<QinIrJsImport> specs = entry.getValue();
            boolean sideEffectOnly = specs.stream().allMatch(spec -> spec.importedName().isBlank());
            if (sideEffectOnly) {
                js.append("import \"").append(escapeJs(entry.getKey())).append("\";\n");
                continue;
            }

            String defaultLocal = null;
            String namespaceLocal = null;
            List<QinIrJsImport> named = new java.util.ArrayList<>();
            for (QinIrJsImport spec : specs) {
                if ("default".equals(spec.importedName())) {
                    defaultLocal = spec.localName();
                } else if ("*".equals(spec.importedName())) {
                    namespaceLocal = spec.localName();
                } else if (!spec.importedName().isBlank()) {
                    named.add(spec);
                }
            }

            js.append("import ");
            boolean hasPrefix = false;
            if (defaultLocal != null && !defaultLocal.isBlank()) {
                js.append(defaultLocal);
                hasPrefix = true;
            }
            if (namespaceLocal != null && !namespaceLocal.isBlank()) {
                if (hasPrefix) {
                    js.append(", ");
                }
                js.append("* as ").append(namespaceLocal);
                hasPrefix = true;
            }
            if (!named.isEmpty()) {
                if (hasPrefix) {
                    js.append(", ");
                }
                js.append("{ ");
                for (int i = 0; i < named.size(); i++) {
                    QinIrJsImport spec = named.get(i);
                    js.append(spec.importedName());
                    if (!spec.importedName().equals(spec.localName())) {
                        js.append(" as ").append(spec.localName());
                    }
                    if (i < named.size() - 1) {
                        js.append(", ");
                    }
                }
                js.append(" }");
            }

            if (!hasPrefix && named.isEmpty()) {
                js.append("\"").append(escapeJs(entry.getKey())).append("\";\n");
                continue;
            }

            js.append(" from \"").append(escapeJs(entry.getKey())).append("\";\n");
        }
        js.append("\n");
    }

    private void ensureNoUnsupportedJavaInterop(QinIrProgram program) {
        if (!program.javaInstanceMethodCalls().isEmpty()) {
            QinIrJavaInstanceMethodCall call = program.javaInstanceMethodCalls().get(0);
            throw new IllegalArgumentException(
                    "JS backend does not support Java instance method interop: "
                            + call.ownerBinaryName() + "." + call.methodName());
        }
        if (!program.javaInstanceConsoleLogs().isEmpty()) {
            QinIrConsoleLogJavaInstanceCall call = program.javaInstanceConsoleLogs().get(0);
            throw new IllegalArgumentException(
                    "JS backend does not support Java instance console interop: "
                            + call.ownerBinaryName() + "." + call.methodName());
        }
        for (QinIrConstDeclaration declaration : program.declarations()) {
            if (declaration.initializer() instanceof QinIrJavaNewExpression javaNewExpression) {
                throw new IllegalArgumentException(
                        "JS backend does not support Java constructor interop: " + javaNewExpression.ownerBinaryName());
            }
        }
    }

    private void emitObjectLiteral(StringBuilder js, QinIrObjectLiteral objectLiteral) {
        js.append("{ ");
        List<QinIrObjectProperty> properties = objectLiteral.properties();
        for (int i = 0; i < properties.size(); i++) {
            QinIrObjectProperty property = properties.get(i);
            js.append(property.key()).append(": ");
            emitExpression(js, property.value());
            if (i < properties.size() - 1) {
                js.append(", ");
            }
        }
        js.append(" }");
    }

    private void emitConsoleLogs(
            StringBuilder js,
            Map<String, QinIrExpression> declarations,
            List<QinIrConsoleLogStatement> consoleLogs) {
        for (QinIrConsoleLogStatement consoleLog : consoleLogs) {
            QinIrExpression declaration = declarations.get(consoleLog.objectName());
            if (!(declaration instanceof QinIrObjectLiteral objectLiteral)) {
                throw new IllegalArgumentException(
                        "console.log(object.property) requires object literal declaration: " + consoleLog.objectName());
            }
            boolean propertyExists = objectLiteral.properties().stream()
                    .anyMatch(property -> property.key().equals(consoleLog.propertyName()));
            if (!propertyExists) {
                throw new IllegalArgumentException(
                        "Unknown property in console.log: " + consoleLog.propertyName());
            }

            js.append("  console.log(")
                    .append(consoleLog.objectName())
                    .append(".")
                    .append(consoleLog.propertyName())
                    .append(");\n");
        }
    }

    private void emitConsoleValueLogs(
            StringBuilder js,
            List<QinIrConsoleLogValue> consoleValueLogs) {
        for (QinIrConsoleLogValue consoleValueLog : consoleValueLogs) {
            js.append("  console.log(");
            emitExpression(js, consoleValueLog.value());
            js.append(");\n");
        }
    }

    private void emitJavaStaticConsoleLogs(
            StringBuilder js,
            List<QinIrConsoleLogJavaStaticCall> javaStaticConsoleLogs) {
        for (QinIrConsoleLogJavaStaticCall call : javaStaticConsoleLogs) {
            js.append("  console.log(")
                    .append(call.receiverName())
                    .append(".")
                    .append(call.methodName())
                    .append("(");
            emitArguments(js, call.arguments());
            js.append("));\n");
        }
    }

    private void emitExpression(StringBuilder js, QinIrExpression expression) {
        if (expression instanceof QinIrNumberLiteral numberLiteral) {
            js.append(numberLiteral.value());
            return;
        }
        if (expression instanceof QinIrStringLiteral stringLiteral) {
            js.append("\"").append(escapeJs(stringLiteral.value())).append("\"");
            return;
        }
        if (expression instanceof QinIrBooleanLiteral booleanLiteral) {
            js.append(booleanLiteral.value() ? "true" : "false");
            return;
        }
        if (expression instanceof QinIrNullLiteral) {
            js.append("null");
            return;
        }
        if (expression instanceof QinIrMemberAccessExpression memberAccessExpression) {
            js.append(memberAccessExpression.objectName())
                    .append(".")
                    .append(memberAccessExpression.propertyName());
            return;
        }
        if (expression instanceof QinIrIdentifierReference identifierReference) {
            js.append(identifierReference.name());
            return;
        }
        if (expression instanceof QinIrBuiltinCallExpression builtinCallExpression) {
            if ("Global".equals(builtinCallExpression.receiverName())) {
                js.append(builtinCallExpression.methodName()).append("(");
            } else {
                js.append(builtinCallExpression.receiverName())
                        .append(".")
                        .append(builtinCallExpression.methodName())
                        .append("(");
            }
            emitArguments(js, builtinCallExpression.arguments());
            js.append(")");
            return;
        }
        if (expression instanceof QinIrObjectLiteral objectLiteral) {
            emitObjectLiteral(js, objectLiteral);
            return;
        }
        throw new IllegalArgumentException("Unsupported expression: " + expression.getClass().getSimpleName());
    }

    private void emitArguments(StringBuilder js, List<QinIrExpression> arguments) {
        for (int i = 0; i < arguments.size(); i++) {
            emitExpression(js, arguments.get(i));
            if (i < arguments.size() - 1) {
                js.append(", ");
            }
        }
    }

    private String escapeJs(String value) {
        return value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"");
    }

    private String lastDeclarationName(List<QinIrConstDeclaration> declarations) {
        if (declarations.isEmpty()) {
            return null;
        }
        return declarations.get(declarations.size() - 1).name();
    }

}
