package com.qin.lang.backend.js;

import com.qin.lang.ir.QinIrBuiltinCallExpression;
import com.qin.lang.ir.QinIrAssignmentExpression;
import com.qin.lang.ir.QinIrBooleanLiteral;
import com.qin.lang.ir.QinIrClassDeclaration;
import com.qin.lang.ir.QinIrConstDeclaration;
import com.qin.lang.ir.QinIrConsoleLogJavaInstanceCall;
import com.qin.lang.ir.QinIrConsoleLogJavaStaticCall;
import com.qin.lang.ir.QinIrConsoleLogStatement;
import com.qin.lang.ir.QinIrConsoleLogValue;
import com.qin.lang.ir.QinIrDoWhileExpression;
import com.qin.lang.ir.QinIrExpression;
import com.qin.lang.ir.QinIrExpressionStatement;
import com.qin.lang.ir.QinIrFieldDeclaration;
import com.qin.lang.ir.QinIrForExpression;
import com.qin.lang.ir.QinIrFunctionLiteral;
import com.qin.lang.ir.QinIrIdentifierReference;
import com.qin.lang.ir.QinIrIfExpression;
import com.qin.lang.ir.QinIrInstanceMethodCallExpression;
import com.qin.lang.ir.QinIrJavaImport;
import com.qin.lang.ir.QinIrJavaInstanceMethodCall;
import com.qin.lang.ir.QinIrJsImport;
import com.qin.lang.ir.QinIrJavaNewExpression;
import com.qin.lang.ir.QinIrLetExpression;
import com.qin.lang.ir.QinIrLocalVariableDeclaration;
import com.qin.lang.ir.QinIrMemberAccessExpression;
import com.qin.lang.ir.QinIrNullLiteral;
import com.qin.lang.ir.QinIrNumberLiteral;
import com.qin.lang.ir.QinIrObjectLiteral;
import com.qin.lang.ir.QinIrObjectProperty;
import com.qin.lang.ir.QinIrParameter;
import com.qin.lang.ir.QinIrProgram;
import com.qin.lang.ir.QinIrSequenceExpression;
import com.qin.lang.ir.QinIrStaticMethodCallExpression;
import com.qin.lang.ir.QinIrStringLiteral;
import com.qin.lang.ir.QinIrMethodDeclaration;
import com.qin.lang.ir.QinIrPropertyAccessExpression;
import com.qin.lang.ir.QinIrThisExpression;
import com.qin.lang.ir.QinIrWhileExpression;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Minimal JavaScript backend for Qin IR.
 */
public final class QinJsBackend {
    public String compileProgram(QinIrProgram program) {
        Objects.requireNonNull(program, "program cannot be null");

        StringBuilder js = new StringBuilder();
        js.append("// Generated by Qin JS backend\n");
        Map<String, String> javaAliases = new LinkedHashMap<>();
        emitJavaAliases(js, program.javaImports(), javaAliases);
        emitJavaRuntimeAliasesForProgram(js, program, javaAliases);
        emitBuiltinRuntimeHelpers(js, program);
        emitJsImports(js, program.jsImports());
        emitClassDeclarations(js, program.classDeclarations());

        Map<String, QinIrExpression> declarationMap = new LinkedHashMap<>();
        for (QinIrConstDeclaration declaration : program.declarations()) {
            js.append("const ").append(declaration.name()).append(" = ");
            emitExpression(js, declaration.initializer());
            js.append(";\n");
            declarationMap.put(declaration.name(), declaration.initializer());
        }
        if (!declarationMap.isEmpty()) {
            js.append("\n");
        }

        js.append("function run() {\n");
        emitRuntimeStatements(js, program, declarationMap);
        String returnName = lastDeclarationName(program.declarations());
        if (returnName != null) {
            js.append("  return ").append(returnName).append(";\n");
        } else {
            js.append("  return null;\n");
        }
        js.append("}\n\n");
        js.append("const __qinResult = run();\n");
        js.append("if (typeof globalThis !== 'undefined') {\n");
        js.append("  globalThis.__qinResult = __qinResult;\n");
        js.append("}\n");

        return js.toString();
    }

    private void emitJavaAliases(
            StringBuilder js,
            List<QinIrJavaImport> javaImports,
            Map<String, String> javaAliases) {
        for (QinIrJavaImport javaImport : javaImports) {
            emitJavaRuntimeAlias(js, javaImport.localName(), javaImport.ownerBinaryName(), javaAliases);
        }
        if (!javaImports.isEmpty()) {
            js.append("\n");
        }
    }

    private void emitJavaRuntimeAliasesForProgram(
            StringBuilder js,
            QinIrProgram program,
            Map<String, String> javaAliases) {
        for (QinIrConstDeclaration declaration : program.declarations()) {
            emitJavaRuntimeAliasesForExpression(js, declaration.initializer(), javaAliases);
        }
        for (QinIrExpressionStatement expressionStatement : program.expressionStatements()) {
            emitJavaRuntimeAliasesForExpression(js, expressionStatement.expression(), javaAliases);
        }
        for (QinIrConsoleLogValue consoleValueLog : program.consoleValueLogs()) {
            emitJavaRuntimeAliasesForExpression(js, consoleValueLog.value(), javaAliases);
        }
        for (QinIrConsoleLogJavaStaticCall call : program.javaStaticConsoleLogs()) {
            emitJavaRuntimeAlias(js, call.receiverName(), call.ownerBinaryName(), javaAliases);
            for (QinIrExpression argument : call.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
        }
        for (QinIrJavaInstanceMethodCall call : program.javaInstanceMethodCalls()) {
            for (QinIrExpression argument : call.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
        }
        for (QinIrConsoleLogJavaInstanceCall call : program.javaInstanceConsoleLogs()) {
            for (QinIrExpression argument : call.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
        }
        for (QinIrClassDeclaration classDeclaration : program.classDeclarations()) {
            for (QinIrFieldDeclaration field : classDeclaration.fields()) {
                emitJavaRuntimeAliasesForExpression(js, field.initializer(), javaAliases);
            }
            for (QinIrMethodDeclaration method : classDeclaration.methods()) {
                emitJavaRuntimeAliasesForExpression(js, method.returnExpression(), javaAliases);
            }
        }
    }

    private void emitJavaRuntimeAliasesForExpression(
            StringBuilder js,
            QinIrExpression expression,
            Map<String, String> javaAliases) {
        if (expression == null) {
            return;
        }
        if (expression instanceof QinIrAssignmentExpression assignmentExpression) {
            emitJavaRuntimeAliasesForExpression(js, assignmentExpression.target(), javaAliases);
            emitJavaRuntimeAliasesForExpression(js, assignmentExpression.value(), javaAliases);
            return;
        }
        if (expression instanceof QinIrIfExpression ifExpression) {
            emitJavaRuntimeAliasesForExpression(js, ifExpression.test(), javaAliases);
            emitJavaRuntimeAliasesForExpression(js, ifExpression.consequent(), javaAliases);
            emitJavaRuntimeAliasesForExpression(js, ifExpression.alternate(), javaAliases);
            return;
        }
        if (expression instanceof QinIrFunctionLiteral functionLiteral) {
            emitJavaRuntimeAliasesForExpression(js, functionLiteral.returnExpression(), javaAliases);
            return;
        }
        if (expression instanceof QinIrForExpression forExpression) {
            for (QinIrLocalVariableDeclaration declaration : forExpression.initializerDeclarations()) {
                emitJavaRuntimeAliasesForExpression(js, declaration.initializer(), javaAliases);
            }
            for (QinIrExpression initializerExpression : forExpression.initializerExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, initializerExpression, javaAliases);
            }
            emitJavaRuntimeAliasesForExpression(js, forExpression.test(), javaAliases);
            for (QinIrExpression updateExpression : forExpression.updateExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, updateExpression, javaAliases);
            }
            for (QinIrLocalVariableDeclaration declaration : forExpression.bodyLocalDeclarations()) {
                emitJavaRuntimeAliasesForExpression(js, declaration.initializer(), javaAliases);
            }
            for (QinIrExpression bodyExpression : forExpression.bodyExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, bodyExpression, javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrDoWhileExpression doWhileExpression) {
            for (QinIrLocalVariableDeclaration declaration : doWhileExpression.localDeclarations()) {
                emitJavaRuntimeAliasesForExpression(js, declaration.initializer(), javaAliases);
            }
            for (QinIrExpression bodyExpression : doWhileExpression.bodyExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, bodyExpression, javaAliases);
            }
            emitJavaRuntimeAliasesForExpression(js, doWhileExpression.test(), javaAliases);
            return;
        }
        if (expression instanceof QinIrWhileExpression whileExpression) {
            emitJavaRuntimeAliasesForExpression(js, whileExpression.test(), javaAliases);
            for (QinIrLocalVariableDeclaration declaration : whileExpression.localDeclarations()) {
                emitJavaRuntimeAliasesForExpression(js, declaration.initializer(), javaAliases);
            }
            for (QinIrExpression bodyExpression : whileExpression.bodyExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, bodyExpression, javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrJavaNewExpression javaNewExpression) {
            emitJavaRuntimeAlias(
                    js,
                    javaNewExpression.classLocalName(),
                    javaNewExpression.ownerBinaryName(),
                    javaAliases);
            for (QinIrExpression argument : javaNewExpression.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrStaticMethodCallExpression staticMethodCallExpression) {
            emitJavaRuntimeAlias(
                    js,
                    staticMethodCallExpression.classLocalName(),
                    staticMethodCallExpression.ownerBinaryName(),
                    javaAliases);
            for (QinIrExpression argument : staticMethodCallExpression.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrInstanceMethodCallExpression instanceMethodCallExpression) {
            emitJavaRuntimeAliasesForExpression(js, instanceMethodCallExpression.receiver(), javaAliases);
            for (QinIrExpression argument : instanceMethodCallExpression.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrLetExpression letExpression) {
            for (QinIrLocalVariableDeclaration declaration : letExpression.localDeclarations()) {
                emitJavaRuntimeAliasesForExpression(js, declaration.initializer(), javaAliases);
            }
            for (QinIrExpression leadingExpression : letExpression.leadingExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, leadingExpression, javaAliases);
            }
            emitJavaRuntimeAliasesForExpression(js, letExpression.resultExpression(), javaAliases);
            return;
        }
        if (expression instanceof QinIrSequenceExpression sequenceExpression) {
            for (QinIrExpression leadingExpression : sequenceExpression.leadingExpressions()) {
                emitJavaRuntimeAliasesForExpression(js, leadingExpression, javaAliases);
            }
            emitJavaRuntimeAliasesForExpression(js, sequenceExpression.resultExpression(), javaAliases);
            return;
        }
        if (expression instanceof QinIrBuiltinCallExpression builtinCallExpression) {
            for (QinIrExpression argument : builtinCallExpression.arguments()) {
                emitJavaRuntimeAliasesForExpression(js, argument, javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrObjectLiteral objectLiteral) {
            for (QinIrObjectProperty property : objectLiteral.properties()) {
                emitJavaRuntimeAliasesForExpression(js, property.value(), javaAliases);
            }
            return;
        }
        if (expression instanceof QinIrPropertyAccessExpression propertyAccessExpression) {
            emitJavaRuntimeAliasesForExpression(js, propertyAccessExpression.receiver(), javaAliases);
        }
    }

    private void emitJavaRuntimeAlias(
            StringBuilder js,
            String localName,
            String ownerBinaryName,
            Map<String, String> javaAliases) {
        if (javaAliases.containsKey(localName)) {
            return;
        }
        switch (ownerBinaryName) {
            case "java.lang.Math" -> {
                if (!"Math".equals(localName)) {
                    js.append("const ").append(localName).append(" = Math;\n");
                }
            }
            case "java.lang.StringBuilder" -> {
                emitJavaLangStringBuilderRuntime(js);
                js.append("const ").append(localName).append(" = __QinJavaLangStringBuilder;\n");
            }
            case "java.util.ArrayList" -> {
                emitJavaUtilArrayListRuntime(js);
                js.append("const ").append(localName).append(" = __QinJavaUtilArrayList;\n");
            }
            case "java.util.HashMap" -> {
                emitJavaUtilHashMapRuntime(js);
                js.append("const ").append(localName).append(" = __QinJavaUtilHashMap;\n");
            }
            case "java.util.Objects" -> {
                emitJavaUtilObjectsRuntime(js);
                js.append("const ").append(localName).append(" = __QinJavaUtilObjects;\n");
            }
            default -> throw new IllegalArgumentException(
                    "JS backend does not support Java stdlib interop yet: " + ownerBinaryName);
        }
        javaAliases.put(localName, ownerBinaryName);
    }

    private void emitJavaLangStringBuilderRuntime(StringBuilder js) {
        if (js.indexOf("class __QinJavaLangStringBuilder") >= 0) {
            return;
        }
        js.append("""
                class __QinJavaLangStringBuilder {
                  constructor(initialValue) {
                    this.__text = "";
                    if (initialValue != null) {
                      this.__text += String(initialValue);
                    }
                  }
                  append(value) {
                    this.__text += String(value);
                    return this;
                  }
                  length() {
                    return this.__text.length;
                  }
                  charAt(index) {
                    return this.__text.charAt(index);
                  }
                  setLength(length) {
                    this.__text = this.__text.slice(0, length);
                  }
                  toString() {
                    return this.__text;
                  }
                }
                """);
    }

    private void emitJavaUtilArrayListRuntime(StringBuilder js) {
        if (js.indexOf("class __QinJavaUtilArrayList") >= 0) {
            return;
        }
        js.append("""
                class __QinJavaUtilArrayList {
                  constructor(initialValues) {
                    this.__items = [];
                    if (initialValues != null) {
                      for (const item of initialValues) {
                        this.__items.push(item);
                      }
                    }
                  }
                  add(value) {
                    this.__items.push(value);
                    return true;
                  }
                  get(index) {
                    return this.__items[index];
                  }
                  size() {
                    return this.__items.length;
                  }
                  isEmpty() {
                    return this.__items.length === 0;
                  }
                  clear() {
                    this.__items.length = 0;
                  }
                  toArray() {
                    return this.__items.slice();
                  }
                  [Symbol.iterator]() {
                    return this.__items[Symbol.iterator]();
                  }
                }
                """);
    }

    private void emitJavaUtilHashMapRuntime(StringBuilder js) {
        if (js.indexOf("class __QinJavaUtilHashMap") >= 0) {
            return;
        }
        js.append("""
                class __QinJavaUtilHashMap {
                  constructor(initialEntries) {
                    this.__entries = new Map();
                    if (initialEntries != null) {
                      for (const entry of initialEntries) {
                        this.__entries.set(entry[0], entry[1]);
                      }
                    }
                  }
                  put(key, value) {
                    const previous = this.__entries.has(key) ? this.__entries.get(key) : null;
                    this.__entries.set(key, value);
                    return previous;
                  }
                  get(key) {
                    return this.__entries.has(key) ? this.__entries.get(key) : null;
                  }
                  containsKey(key) {
                    return this.__entries.has(key);
                  }
                  remove(key) {
                    const previous = this.__entries.has(key) ? this.__entries.get(key) : null;
                    this.__entries.delete(key);
                    return previous;
                  }
                  size() {
                    return this.__entries.size;
                  }
                  isEmpty() {
                    return this.__entries.size === 0;
                  }
                  clear() {
                    this.__entries.clear();
                  }
                }
                """);
    }

    private void emitJavaUtilObjectsRuntime(StringBuilder js) {
        if (js.indexOf("const __QinJavaUtilObjects") >= 0) {
            return;
        }
        js.append("""
                const __QinJavaUtilObjects = {
                  toString(value, nullDefault) {
                    if (value == null) {
                      return arguments.length >= 2 ? nullDefault : "null";
                    }
                    return String(value);
                  }
                };
                """);
    }

    private void emitJsImports(StringBuilder js, List<QinIrJsImport> jsImports) {
        if (jsImports == null || jsImports.isEmpty()) {
            return;
        }

        Map<String, List<QinIrJsImport>> grouped = new LinkedHashMap<>();
        for (QinIrJsImport jsImport : jsImports) {
            grouped.computeIfAbsent(jsImport.moduleName(), ignored -> new java.util.ArrayList<>())
                    .add(jsImport);
        }

        for (Map.Entry<String, List<QinIrJsImport>> entry : grouped.entrySet()) {
            List<QinIrJsImport> specs = entry.getValue();
            boolean sideEffectOnly = specs.stream().allMatch(spec -> spec.importedName().isBlank());
            if (sideEffectOnly) {
                js.append("import \"").append(escapeJs(entry.getKey())).append("\";\n");
                continue;
            }

            String defaultLocal = null;
            String namespaceLocal = null;
            List<QinIrJsImport> named = new java.util.ArrayList<>();
            for (QinIrJsImport spec : specs) {
                if ("default".equals(spec.importedName())) {
                    defaultLocal = spec.localName();
                } else if ("*".equals(spec.importedName())) {
                    namespaceLocal = spec.localName();
                } else if (!spec.importedName().isBlank()) {
                    named.add(spec);
                }
            }

            js.append("import ");
            boolean hasPrefix = false;
            if (defaultLocal != null && !defaultLocal.isBlank()) {
                js.append(defaultLocal);
                hasPrefix = true;
            }
            if (namespaceLocal != null && !namespaceLocal.isBlank()) {
                if (hasPrefix) {
                    js.append(", ");
                }
                js.append("* as ").append(namespaceLocal);
                hasPrefix = true;
            }
            if (!named.isEmpty()) {
                if (hasPrefix) {
                    js.append(", ");
                }
                js.append("{ ");
                for (int i = 0; i < named.size(); i++) {
                    QinIrJsImport spec = named.get(i);
                    js.append(spec.importedName());
                    if (!spec.importedName().equals(spec.localName())) {
                        js.append(" as ").append(spec.localName());
                    }
                    if (i < named.size() - 1) {
                        js.append(", ");
                    }
                }
                js.append(" }");
            }

            if (!hasPrefix && named.isEmpty()) {
                js.append("\"").append(escapeJs(entry.getKey())).append("\";\n");
                continue;
            }

            js.append(" from \"").append(escapeJs(entry.getKey())).append("\";\n");
        }
        js.append("\n");
    }

    private void emitBuiltinRuntimeHelpers(StringBuilder js, QinIrProgram program) {
        boolean usesBinary = usesBuiltin(program, "__qin_binary__");
        boolean usesLogical = usesBuiltin(program, "__qin_logical__");
        if (!usesBinary && !usesLogical) {
            return;
        }
        if (usesBinary) {
            js.append("""
                    function __qin_binary__(operator, left, right) {
                      switch (operator) {
                        case "+": return left + right;
                        case "-": return left - right;
                        case "*": return left * right;
                        case "/": return left / right;
                        case "%": return left % right;
                        case "==": return left == right;
                        case "!=": return left != right;
                        case "===": return left === right;
                        case "!==": return left !== right;
                        case "<": return left < right;
                        case "<=": return left <= right;
                        case ">": return left > right;
                        case ">=": return left >= right;
                        case "&&": return left && right;
                        case "||": return left || right;
                        default: throw new Error("Unsupported Qin binary operator: " + operator);
                      }
                    }
                    """);
        }
        if (usesLogical) {
            js.append("""
                    function __qin_logical__(operator, left, right) {
                      switch (operator) {
                        case "&&": return left && right;
                        case "||": return left || right;
                        default: throw new Error("Unsupported Qin logical operator: " + operator);
                      }
                    }
                    """);
        }
    }

    private boolean usesBuiltin(QinIrProgram program, String methodName) {
        for (QinIrConstDeclaration declaration : program.declarations()) {
            if (usesBuiltin(declaration.initializer(), methodName)) {
                return true;
            }
        }
        for (QinIrExpressionStatement expressionStatement : program.expressionStatements()) {
            if (usesBuiltin(expressionStatement.expression(), methodName)) {
                return true;
            }
        }
        for (QinIrConsoleLogValue consoleValueLog : program.consoleValueLogs()) {
            if (usesBuiltin(consoleValueLog.value(), methodName)) {
                return true;
            }
        }
        for (QinIrConsoleLogJavaStaticCall call : program.javaStaticConsoleLogs()) {
            for (QinIrExpression argument : call.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
        }
        for (QinIrJavaInstanceMethodCall call : program.javaInstanceMethodCalls()) {
            for (QinIrExpression argument : call.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
        }
        for (QinIrConsoleLogJavaInstanceCall call : program.javaInstanceConsoleLogs()) {
            for (QinIrExpression argument : call.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
        }
        for (QinIrClassDeclaration classDeclaration : program.classDeclarations()) {
            for (QinIrFieldDeclaration field : classDeclaration.fields()) {
                if (usesBuiltin(field.initializer(), methodName)) {
                    return true;
                }
            }
            for (QinIrMethodDeclaration method : classDeclaration.methods()) {
                if (usesBuiltin(method.returnExpression(), methodName)) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean usesBuiltin(QinIrExpression expression, String methodName) {
        if (expression == null) {
            return false;
        }
        if (expression instanceof QinIrAssignmentExpression assignmentExpression) {
            return usesBuiltin(assignmentExpression.target(), methodName)
                    || usesBuiltin(assignmentExpression.value(), methodName);
        }
        if (expression instanceof QinIrIfExpression ifExpression) {
            return usesBuiltin(ifExpression.test(), methodName)
                    || usesBuiltin(ifExpression.consequent(), methodName)
                    || usesBuiltin(ifExpression.alternate(), methodName);
        }
        if (expression instanceof QinIrForExpression forExpression) {
            for (QinIrLocalVariableDeclaration declaration : forExpression.initializerDeclarations()) {
                if (usesBuiltin(declaration.initializer(), methodName)) {
                    return true;
                }
            }
            for (QinIrExpression initializerExpression : forExpression.initializerExpressions()) {
                if (usesBuiltin(initializerExpression, methodName)) {
                    return true;
                }
            }
            if (usesBuiltin(forExpression.test(), methodName)) {
                return true;
            }
            for (QinIrExpression updateExpression : forExpression.updateExpressions()) {
                if (usesBuiltin(updateExpression, methodName)) {
                    return true;
                }
            }
            for (QinIrLocalVariableDeclaration declaration : forExpression.bodyLocalDeclarations()) {
                if (usesBuiltin(declaration.initializer(), methodName)) {
                    return true;
                }
            }
            for (QinIrExpression bodyExpression : forExpression.bodyExpressions()) {
                if (usesBuiltin(bodyExpression, methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrDoWhileExpression doWhileExpression) {
            for (QinIrLocalVariableDeclaration declaration : doWhileExpression.localDeclarations()) {
                if (usesBuiltin(declaration.initializer(), methodName)) {
                    return true;
                }
            }
            for (QinIrExpression bodyExpression : doWhileExpression.bodyExpressions()) {
                if (usesBuiltin(bodyExpression, methodName)) {
                    return true;
                }
            }
            return usesBuiltin(doWhileExpression.test(), methodName);
        }
        if (expression instanceof QinIrWhileExpression whileExpression) {
            if (usesBuiltin(whileExpression.test(), methodName)) {
                return true;
            }
            for (QinIrLocalVariableDeclaration declaration : whileExpression.localDeclarations()) {
                if (usesBuiltin(declaration.initializer(), methodName)) {
                    return true;
                }
            }
            for (QinIrExpression bodyExpression : whileExpression.bodyExpressions()) {
                if (usesBuiltin(bodyExpression, methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrBuiltinCallExpression builtinCallExpression) {
            if (methodName.equals(builtinCallExpression.methodName())) {
                return true;
            }
            for (QinIrExpression argument : builtinCallExpression.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrJavaNewExpression javaNewExpression) {
            for (QinIrExpression argument : javaNewExpression.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrStaticMethodCallExpression staticMethodCallExpression) {
            for (QinIrExpression argument : staticMethodCallExpression.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrInstanceMethodCallExpression instanceMethodCallExpression) {
            if (usesBuiltin(instanceMethodCallExpression.receiver(), methodName)) {
                return true;
            }
            for (QinIrExpression argument : instanceMethodCallExpression.arguments()) {
                if (usesBuiltin(argument, methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrObjectLiteral objectLiteral) {
            for (QinIrObjectProperty property : objectLiteral.properties()) {
                if (usesBuiltin(property.value(), methodName)) {
                    return true;
                }
            }
            return false;
        }
        if (expression instanceof QinIrLetExpression letExpression) {
            for (QinIrLocalVariableDeclaration declaration : letExpression.localDeclarations()) {
                if (usesBuiltin(declaration.initializer(), methodName)) {
                    return true;
                }
            }
            for (QinIrExpression leadingExpression : letExpression.leadingExpressions()) {
                if (usesBuiltin(leadingExpression, methodName)) {
                    return true;
                }
            }
            return usesBuiltin(letExpression.resultExpression(), methodName);
        }
        if (expression instanceof QinIrSequenceExpression sequenceExpression) {
            for (QinIrExpression leadingExpression : sequenceExpression.leadingExpressions()) {
                if (usesBuiltin(leadingExpression, methodName)) {
                    return true;
                }
            }
            return usesBuiltin(sequenceExpression.resultExpression(), methodName);
        }
        if (expression instanceof QinIrPropertyAccessExpression propertyAccessExpression) {
            return usesBuiltin(propertyAccessExpression.receiver(), methodName);
        }
        return false;
    }

    private void emitObjectLiteral(StringBuilder js, QinIrObjectLiteral objectLiteral) {
        js.append("{ ");
        List<QinIrObjectProperty> properties = objectLiteral.properties();
        for (int i = 0; i < properties.size(); i++) {
            QinIrObjectProperty property = properties.get(i);
            js.append(property.key()).append(": ");
            emitExpression(js, property.value());
            if (i < properties.size() - 1) {
                js.append(", ");
            }
        }
        js.append(" }");
    }

    private void emitClassDeclarations(StringBuilder js, List<QinIrClassDeclaration> classDeclarations) {
        for (QinIrClassDeclaration classDeclaration : classDeclarations) {
            if (classDeclaration.superType() != null) {
                throw new IllegalArgumentException(
                        "JS backend does not support Java class extends yet: " + classDeclaration.simpleName());
            }
            js.append("class ").append(classDeclaration.simpleName()).append(" {\n");
            emitClassConstructor(js, classDeclaration.fields());
            for (QinIrMethodDeclaration method : classDeclaration.methods()) {
                emitMethodDeclaration(js, method);
            }
            js.append("}\n");
        }
        if (!classDeclarations.isEmpty()) {
            js.append("\n");
        }
    }

    private void emitClassConstructor(StringBuilder js, List<QinIrFieldDeclaration> fields) {
        js.append("  constructor() {\n");
        for (QinIrFieldDeclaration field : fields) {
            js.append("    this.").append(field.name()).append(" = ");
            if (field.initializer() == null) {
                js.append("null");
            } else {
                emitExpression(js, field.initializer());
            }
            js.append(";\n");
        }
        js.append("  }\n");
    }

    private void emitMethodDeclaration(StringBuilder js, QinIrMethodDeclaration method) {
        js.append("  ").append(method.name()).append("(");
        List<QinIrParameter> parameters = method.parameters();
        for (int i = 0; i < parameters.size(); i++) {
            js.append(parameters.get(i).name());
            if (i < parameters.size() - 1) {
                js.append(", ");
            }
        }
        js.append(") {\n");
        js.append("    return ");
        if (method.returnExpression() == null) {
            js.append("null");
        } else {
            emitExpression(js, method.returnExpression());
        }
        js.append(";\n");
        js.append("  }\n");
    }

    private void emitConsoleLogs(
            StringBuilder js,
            Map<String, QinIrExpression> declarations,
            List<QinIrConsoleLogStatement> consoleLogs) {
        for (QinIrConsoleLogStatement consoleLog : consoleLogs) {
            QinIrExpression declaration = declarations.get(consoleLog.objectName());
            if (!(declaration instanceof QinIrObjectLiteral objectLiteral)) {
                throw new IllegalArgumentException(
                        "console.log(object.property) requires object literal declaration: " + consoleLog.objectName());
            }
            boolean propertyExists = objectLiteral.properties().stream()
                    .anyMatch(property -> property.key().equals(consoleLog.propertyName()));
            if (!propertyExists) {
                throw new IllegalArgumentException(
                        "Unknown property in console.log: " + consoleLog.propertyName());
            }

            js.append("  console.log(")
                    .append(consoleLog.objectName())
                    .append(".")
                    .append(consoleLog.propertyName())
                    .append(");\n");
        }
    }

    private void emitConsoleValueLogs(
            StringBuilder js,
            List<QinIrConsoleLogValue> consoleValueLogs) {
        for (QinIrConsoleLogValue consoleValueLog : consoleValueLogs) {
            js.append("  console.log(");
            emitExpression(js, consoleValueLog.value());
            js.append(");\n");
        }
    }

    private void emitExpressionStatements(
            StringBuilder js,
            List<QinIrExpressionStatement> expressionStatements) {
        for (QinIrExpressionStatement expressionStatement : expressionStatements) {
            js.append("  ");
            emitExpression(js, expressionStatement.expression());
            js.append(";\n");
        }
    }

    private void emitJavaStaticConsoleLogs(
            StringBuilder js,
            List<QinIrConsoleLogJavaStaticCall> javaStaticConsoleLogs) {
        for (QinIrConsoleLogJavaStaticCall call : javaStaticConsoleLogs) {
            emitJavaStaticConsoleLog(js, call);
        }
    }

    private void emitJavaStaticConsoleLog(StringBuilder js, QinIrConsoleLogJavaStaticCall call) {
        js.append("  console.log(")
                .append(call.receiverName())
                .append(".")
                .append(call.methodName())
                .append("(");
        emitArguments(js, call.arguments());
        js.append("));\n");
    }

    private void emitJavaInstanceMethodCall(StringBuilder js, QinIrJavaInstanceMethodCall call) {
        ensureSupportedJavaOwner(call.ownerBinaryName());
        js.append("  ")
                .append(call.receiverName())
                .append(".")
                .append(call.methodName())
                .append("(");
        emitArguments(js, call.arguments());
        js.append(");\n");
    }

    private void emitJavaInstanceConsoleLog(StringBuilder js, QinIrConsoleLogJavaInstanceCall call) {
        ensureSupportedJavaOwner(call.ownerBinaryName());
        js.append("  console.log(")
                .append(call.receiverName())
                .append(".")
                .append(call.methodName())
                .append("(");
        emitArguments(js, call.arguments());
        js.append("));\n");
    }

    private void emitRuntimeStatements(
            StringBuilder js,
            QinIrProgram program,
            Map<String, QinIrExpression> declarationMap) {
        if (program.executionSteps().isEmpty()) {
            emitExpressionStatements(js, program.expressionStatements());
            emitConsoleValueLogs(js, program.consoleValueLogs());
            emitConsoleLogs(js, declarationMap, program.consoleLogs());
            emitJavaStaticConsoleLogs(js, program.javaStaticConsoleLogs());
            for (QinIrJavaInstanceMethodCall call : program.javaInstanceMethodCalls()) {
                emitJavaInstanceMethodCall(js, call);
            }
            for (QinIrConsoleLogJavaInstanceCall call : program.javaInstanceConsoleLogs()) {
                emitJavaInstanceConsoleLog(js, call);
            }
            return;
        }

        for (QinIrProgram.TopLevelExecutionStep step : program.executionSteps()) {
            switch (step.kind()) {
                case DECLARATION -> {
                    // Declarations are emitted as module-level const bindings above run().
                }
                case EXPRESSION_STATEMENT -> emitExpressionStatement(
                        js,
                        program.expressionStatements().get(step.index()));
                case CONSOLE_VALUE -> emitConsoleValueLog(
                        js,
                        program.consoleValueLogs().get(step.index()));
                case CONSOLE_OBJECT -> emitConsoleLog(
                        js,
                        declarationMap,
                        program.consoleLogs().get(step.index()));
                case JAVA_STATIC_CONSOLE -> emitJavaStaticConsoleLog(
                        js,
                        program.javaStaticConsoleLogs().get(step.index()));
                case JAVA_INSTANCE_CALL -> emitJavaInstanceMethodCall(
                        js,
                        program.javaInstanceMethodCalls().get(step.index()));
                case JAVA_INSTANCE_CONSOLE -> emitJavaInstanceConsoleLog(
                        js,
                        program.javaInstanceConsoleLogs().get(step.index()));
            }
        }
    }

    private void emitExpressionStatement(StringBuilder js, QinIrExpressionStatement expressionStatement) {
        js.append("  ");
        emitExpression(js, expressionStatement.expression());
        js.append(";\n");
    }

    private void emitConsoleValueLog(StringBuilder js, QinIrConsoleLogValue consoleValueLog) {
        js.append("  console.log(");
        emitExpression(js, consoleValueLog.value());
        js.append(");\n");
    }

    private void emitConsoleLog(
            StringBuilder js,
            Map<String, QinIrExpression> declarations,
            QinIrConsoleLogStatement consoleLog) {
        QinIrExpression declaration = declarations.get(consoleLog.objectName());
        if (!(declaration instanceof QinIrObjectLiteral objectLiteral)) {
            throw new IllegalArgumentException(
                    "console.log(object.property) requires object literal declaration: " + consoleLog.objectName());
        }
        boolean propertyExists = objectLiteral.properties().stream()
                .anyMatch(property -> property.key().equals(consoleLog.propertyName()));
        if (!propertyExists) {
            throw new IllegalArgumentException(
                    "Unknown property in console.log: " + consoleLog.propertyName());
        }

        js.append("  console.log(")
                .append(consoleLog.objectName())
                .append(".")
                .append(consoleLog.propertyName())
                .append(");\n");
    }

    private void emitExpression(StringBuilder js, QinIrExpression expression) {
        if (expression instanceof QinIrNumberLiteral numberLiteral) {
            js.append(numberLiteral.value());
            return;
        }
        if (expression instanceof QinIrStringLiteral stringLiteral) {
            js.append("\"").append(escapeJs(stringLiteral.value())).append("\"");
            return;
        }
        if (expression instanceof QinIrBooleanLiteral booleanLiteral) {
            js.append(booleanLiteral.value() ? "true" : "false");
            return;
        }
        if (expression instanceof QinIrNullLiteral) {
            js.append("null");
            return;
        }
        if (expression instanceof QinIrMemberAccessExpression memberAccessExpression) {
            js.append(memberAccessExpression.objectName())
                    .append(".")
                    .append(memberAccessExpression.propertyName());
            return;
        }
        if (expression instanceof QinIrThisExpression) {
            js.append("this");
            return;
        }
        if (expression instanceof QinIrAssignmentExpression assignmentExpression) {
            emitExpression(js, assignmentExpression.target());
            js.append(" ").append(assignmentExpression.operator()).append(" ");
            emitExpression(js, assignmentExpression.value());
            return;
        }
        if (expression instanceof QinIrIfExpression ifExpression) {
            emitIfExpression(js, ifExpression);
            return;
        }
        if (expression instanceof QinIrForExpression forExpression) {
            emitForExpression(js, forExpression);
            return;
        }
        if (expression instanceof QinIrDoWhileExpression doWhileExpression) {
            emitDoWhileExpression(js, doWhileExpression);
            return;
        }
        if (expression instanceof QinIrWhileExpression whileExpression) {
            emitWhileExpression(js, whileExpression);
            return;
        }
        if (expression instanceof QinIrPropertyAccessExpression propertyAccessExpression) {
            emitExpression(js, propertyAccessExpression.receiver());
            js.append(".").append(propertyAccessExpression.propertyName());
            return;
        }
        if (expression instanceof QinIrInstanceMethodCallExpression instanceMethodCallExpression) {
            emitExpression(js, instanceMethodCallExpression.receiver());
            js.append(".")
                    .append(instanceMethodCallExpression.methodName())
                    .append("(");
            emitArguments(js, instanceMethodCallExpression.arguments());
            js.append(")");
            return;
        }
        if (expression instanceof QinIrStaticMethodCallExpression staticMethodCallExpression) {
            ensureSupportedJavaOwner(staticMethodCallExpression.ownerBinaryName());
            js.append(staticMethodCallExpression.classLocalName())
                    .append(".")
                    .append(staticMethodCallExpression.methodName())
                    .append("(");
            emitArguments(js, staticMethodCallExpression.arguments());
            js.append(")");
            return;
        }
        if (expression instanceof QinIrJavaNewExpression javaNewExpression) {
            ensureSupportedJavaOwner(javaNewExpression.ownerBinaryName());
            js.append("new ")
                    .append(javaNewExpression.classLocalName())
                    .append("(");
            emitArguments(js, javaNewExpression.arguments());
            js.append(")");
            return;
        }
        if (expression instanceof QinIrIdentifierReference identifierReference) {
            js.append(identifierReference.name());
            return;
        }
        if (expression instanceof QinIrFunctionLiteral functionLiteral) {
            js.append("() => {\n");
            js.append("      return ");
            emitExpression(js, functionLiteral.returnExpression());
            js.append(";\n");
            js.append("    }");
            return;
        }
        if (expression instanceof QinIrBuiltinCallExpression builtinCallExpression) {
            if ("Global".equals(builtinCallExpression.receiverName())) {
                js.append(builtinCallExpression.methodName()).append("(");
            } else {
                js.append(builtinCallExpression.receiverName())
                        .append(".")
                        .append(builtinCallExpression.methodName())
                        .append("(");
            }
            emitArguments(js, builtinCallExpression.arguments());
            js.append(")");
            return;
        }
        if (expression instanceof QinIrLetExpression letExpression) {
            emitLetExpression(js, letExpression);
            return;
        }
        if (expression instanceof QinIrSequenceExpression sequenceExpression) {
            emitSequenceExpression(js, sequenceExpression);
            return;
        }
        if (expression instanceof QinIrObjectLiteral objectLiteral) {
            emitObjectLiteral(js, objectLiteral);
            return;
        }
        throw new IllegalArgumentException("Unsupported expression: " + expression.getClass().getSimpleName());
    }

    private void emitLetExpression(StringBuilder js, QinIrLetExpression letExpression) {
        js.append("(() => {\n");
        for (QinIrLocalVariableDeclaration declaration : letExpression.localDeclarations()) {
            js.append("      let ").append(declaration.name()).append(" = ");
            emitExpression(js, declaration.initializer());
            js.append(";\n");
        }
        for (QinIrExpression leadingExpression : letExpression.leadingExpressions()) {
            js.append("      ");
            emitExpression(js, leadingExpression);
            js.append(";\n");
        }
        js.append("      return ");
        emitExpression(js, letExpression.resultExpression());
        js.append(";\n");
        js.append("    })()");
    }

    private void emitIfExpression(StringBuilder js, QinIrIfExpression ifExpression) {
        js.append("(() => {\n");
        js.append("      if (");
        emitExpression(js, ifExpression.test());
        js.append(") {\n");
        js.append("        return ");
        emitExpression(js, ifExpression.consequent());
        js.append(";\n");
        js.append("      }\n");
        js.append("      return ");
        emitExpression(js, ifExpression.alternate());
        js.append(";\n");
        js.append("    })()");
    }

    private void emitWhileExpression(StringBuilder js, QinIrWhileExpression whileExpression) {
        js.append("(() => {\n");
        js.append("      while (");
        emitExpression(js, whileExpression.test());
        js.append(") {\n");
        for (QinIrLocalVariableDeclaration declaration : whileExpression.localDeclarations()) {
            js.append("        let ").append(declaration.name()).append(" = ");
            emitExpression(js, declaration.initializer());
            js.append(";\n");
        }
        for (QinIrExpression bodyExpression : whileExpression.bodyExpressions()) {
            js.append("        ");
            emitExpression(js, bodyExpression);
            js.append(";\n");
        }
        js.append("      }\n");
        js.append("      return null;\n");
        js.append("    })()");
    }

    private void emitDoWhileExpression(StringBuilder js, QinIrDoWhileExpression doWhileExpression) {
        js.append("(() => {\n");
        js.append("      do {\n");
        for (QinIrLocalVariableDeclaration declaration : doWhileExpression.localDeclarations()) {
            js.append("        let ").append(declaration.name()).append(" = ");
            emitExpression(js, declaration.initializer());
            js.append(";\n");
        }
        for (QinIrExpression bodyExpression : doWhileExpression.bodyExpressions()) {
            js.append("        ");
            emitExpression(js, bodyExpression);
            js.append(";\n");
        }
        js.append("      } while (");
        emitExpression(js, doWhileExpression.test());
        js.append(");\n");
        js.append("      return null;\n");
        js.append("    })()");
    }

    private void emitForExpression(StringBuilder js, QinIrForExpression forExpression) {
        js.append("(() => {\n");
        js.append("      for (");
        emitForInitializers(js, forExpression);
        js.append("; ");
        if (forExpression.test() != null) {
            emitExpression(js, forExpression.test());
        }
        js.append("; ");
        emitCommaSeparatedExpressions(js, forExpression.updateExpressions());
        js.append(") {\n");
        for (QinIrLocalVariableDeclaration declaration : forExpression.bodyLocalDeclarations()) {
            js.append("        let ").append(declaration.name()).append(" = ");
            emitExpression(js, declaration.initializer());
            js.append(";\n");
        }
        for (QinIrExpression bodyExpression : forExpression.bodyExpressions()) {
            js.append("        ");
            emitExpression(js, bodyExpression);
            js.append(";\n");
        }
        js.append("      }\n");
        js.append("      return null;\n");
        js.append("    })()");
    }

    private void emitForInitializers(StringBuilder js, QinIrForExpression forExpression) {
        boolean emitted = false;
        if (!forExpression.initializerDeclarations().isEmpty()) {
            js.append("let ");
            for (int i = 0; i < forExpression.initializerDeclarations().size(); i++) {
                if (i > 0) {
                    js.append(", ");
                }
                QinIrLocalVariableDeclaration declaration = forExpression.initializerDeclarations().get(i);
                js.append(declaration.name()).append(" = ");
                emitExpression(js, declaration.initializer());
            }
            emitted = true;
        }
        if (!forExpression.initializerExpressions().isEmpty()) {
            if (emitted) {
                js.append(", ");
            }
            emitCommaSeparatedExpressions(js, forExpression.initializerExpressions());
        }
    }

    private void emitCommaSeparatedExpressions(StringBuilder js, List<QinIrExpression> expressions) {
        for (int i = 0; i < expressions.size(); i++) {
            if (i > 0) {
                js.append(", ");
            }
            emitExpression(js, expressions.get(i));
        }
    }

    private void emitSequenceExpression(StringBuilder js, QinIrSequenceExpression sequenceExpression) {
        js.append("(() => {\n");
        for (QinIrExpression leadingExpression : sequenceExpression.leadingExpressions()) {
            js.append("      ");
            emitExpression(js, leadingExpression);
            js.append(";\n");
        }
        js.append("      return ");
        emitExpression(js, sequenceExpression.resultExpression());
        js.append(";\n");
        js.append("    })()");
    }

    private void ensureSupportedJavaOwner(String ownerBinaryName) {
        if ("java.util.ArrayList".equals(ownerBinaryName)
                || "java.util.HashMap".equals(ownerBinaryName)
                || "java.util.Objects".equals(ownerBinaryName)
                || "java.lang.StringBuilder".equals(ownerBinaryName)
                || "java.lang.Math".equals(ownerBinaryName)) {
            return;
        }
        throw new IllegalArgumentException("JS backend does not support Java stdlib interop yet: " + ownerBinaryName);
    }

    private void emitArguments(StringBuilder js, List<QinIrExpression> arguments) {
        for (int i = 0; i < arguments.size(); i++) {
            emitExpression(js, arguments.get(i));
            if (i < arguments.size() - 1) {
                js.append(", ");
            }
        }
    }

    private String escapeJs(String value) {
        return value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"");
    }

    private String lastDeclarationName(List<QinIrConstDeclaration> declarations) {
        if (declarations.isEmpty()) {
            return null;
        }
        return declarations.get(declarations.size() - 1).name();
    }

}
