import { com_slime_parser_expressions_SlimeAssignmentExpressionParser } from "../expressions/SlimeAssignmentExpressionParser.ts";
import { com_slime_parser_expressions_SlimeBinaryExpressionParser } from "../expressions/SlimeBinaryExpressionParser.ts";
import { com_slime_parser_expressions_SlimeUnaryExpressionParser } from "../expressions/SlimeUnaryExpressionParser.ts";
import { com_slime_parser_expressions_SlimePrimaryExpressionParser } from "../expressions/SlimePrimaryExpressionParser.ts";
import { com_slime_parser_literal_SlimeLiteralParser } from "../literal/SlimeLiteralParser.ts";
import { com_slime_parser_identifier_SlimeIdentifierParser } from "../identifier/SlimeIdentifierParser.ts";
import { com_slime_parser_base_SlimeJavascriptParserBase, com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams, com_slime_parser_base_SlimeJavascriptParserBase$StatementParams, com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams, com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams } from "../base/SlimeJavascriptParserBase.ts";
import { com_subhuti_parser_SubhutiParser } from "../../../subhuti/parser/SubhutiParser.ts";
import { com_subhuti_parser_SubhutiParserFinal } from "../../../subhuti/parser/SubhutiParserFinal.ts";
import { com_subhuti_parser_SubhutiParserCombinators, com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher, com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext, com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext, com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame } from "../../../subhuti/parser/SubhutiParserCombinators.ts";
import { com_subhuti_parser_SubhutiParserCore, com_subhuti_parser_SubhutiParserCore$RuleExecutionResult } from "../../../subhuti/parser/SubhutiParserCore.ts";
import { com_subhuti_parser_SubhutiParserState } from "../../../subhuti/parser/SubhutiParserState.ts";
import { com_subhuti_lookahead_SubhutiTokenLookahead } from "../../../subhuti/lookahead/SubhutiTokenLookahead.ts";
const SlimeAssignmentExpressionParser = com_slime_parser_expressions_SlimeAssignmentExpressionParser;
const SlimeBinaryExpressionParser = com_slime_parser_expressions_SlimeBinaryExpressionParser;
const SlimeUnaryExpressionParser = com_slime_parser_expressions_SlimeUnaryExpressionParser;
const SlimePrimaryExpressionParser = com_slime_parser_expressions_SlimePrimaryExpressionParser;
const SlimeLiteralParser = com_slime_parser_literal_SlimeLiteralParser;
const SlimeIdentifierParser = com_slime_parser_identifier_SlimeIdentifierParser;
const SlimeJavascriptParserBase = com_slime_parser_base_SlimeJavascriptParserBase;
const ExpressionParams = com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams;
const StatementParams = com_slime_parser_base_SlimeJavascriptParserBase$StatementParams;
const DeclarationParams = com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams;
const TemplateLiteralParams = com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams;
const SubhutiParser = com_subhuti_parser_SubhutiParser;
const SubhutiParserFinal = com_subhuti_parser_SubhutiParserFinal;
const SubhutiParserCombinators = com_subhuti_parser_SubhutiParserCombinators;
const StopTokenMatcher = com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher;
const AllowErrorOrBranchContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext;
const AllowErrorContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext;
const ManyTolerantFrame = com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame;
const SubhutiParserCore = com_subhuti_parser_SubhutiParserCore;
const RuleExecutionResult = com_subhuti_parser_SubhutiParserCore$RuleExecutionResult;
const SubhutiParserState = com_subhuti_parser_SubhutiParserState;

// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__ } from "@qin/java-sdk-js";
import { __qin_subhuti_rule_cache_key } from "@qin/java-sdk-js/tooling";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
class com_slime_parser_statements_SlimeStatementParser extends com_slime_parser_expressions_SlimeAssignmentExpressionParser {
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 1: {
        const sourceCode: any = __qin_args[0];
        super(sourceCode);
        this.__qin_constructor_com_slime_parser_statements_SlimeStatementParser_1(sourceCode);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeStatementParser/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_statements_SlimeStatementParser_1(sourceCode: string): void {
    null;
  }
  Statement(...__qin_args: any[]): any {
    if (__qin_args.length === 1 && (__qin_args[0] === null || __qin_args[0] instanceof com_slime_parser_base_SlimeJavascriptParserBase$StatementParams || __qin_structural_object__(__qin_args[0]))) return this.__qin_overload_Statement_1_0(...__qin_args);
    if (__qin_args.length === 0 && true) return this.__qin_overload_Statement_0_1(...__qin_args);
    throw new Error("Unsupported Java overload: Statement/" + __qin_args.length);
  }
  __qin_overload_Statement_1_0(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw___qin_overload_Statement_1_0(params);
    }), "Statement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw___qin_overload_Statement_1_0(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.BlockStatement(params);
    }), __qin_java_functional(() => {
      return this.VariableStatement(params);
    }), __qin_java_functional(() => {
      return this.EmptyStatement();
    }), __qin_java_functional(() => {
      return this.ExpressionStatement(params);
    }), __qin_java_functional(() => {
      return this.IfStatement(params);
    }), __qin_java_functional(() => {
      return this.BreakableStatement(params);
    }), __qin_java_functional(() => {
      return this.ContinueStatement(params);
    }), __qin_java_functional(() => {
      return this.BreakStatement(params);
    }), (() => {
      if (params.returnAllowed()) {
        return __qin_java_functional(() => {
      return this.ReturnStatement(params);
    });
      }
      return null;
    })(), __qin_java_functional(() => {
      return this.WithStatement(params);
    }), __qin_java_functional(() => {
      return this.LabelledStatement(params);
    }), __qin_java_functional(() => {
      return this.ThrowStatement(params);
    }), __qin_java_functional(() => {
      return this.TryStatement(params);
    }), __qin_java_functional(() => {
      return this.DebuggerStatement();
    }));
    return null;
  }
  __qin_overload_Statement_0_1(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw___qin_overload_Statement_0_1();
    }), "Statement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw___qin_overload_Statement_0_1(): any {
    this.Statement(com_slime_parser_base_SlimeJavascriptParserBase$StatementParams.__qin_field_DEFAULT);
    return null;
  }
  BlockStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_BlockStatement(params);
    }), "BlockStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_BlockStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Block(params);
    return null;
  }
  Block(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_Block(params);
    }), "Block", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_Block(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.LBrace();
    this.Option(__qin_java_functional(() => {
      return this.StatementList(params);
    }));
    this.__qin_field_tokenConsumer.RBrace();
    return null;
  }
  StatementList(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_StatementList(params);
    }), "StatementList", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_StatementList(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Many(__qin_java_functional(() => {
      return this.StatementListItem(params);
    }));
    return null;
  }
  StatementListItem(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_StatementListItem(params);
    }), "StatementListItem", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_StatementListItem(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.Declaration(new com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams(params.yield(), params.await(), false));
    }), __qin_java_functional(() => {
      return this.Statement(params);
    }));
    return null;
  }
  VariableStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_VariableStatement(params);
    }), "VariableStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_VariableStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Var();
    this.VariableDeclarationList(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.SemicolonASI();
    return null;
  }
  VariableDeclarationList(params: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_VariableDeclarationList(params);
    }), "VariableDeclarationList", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_VariableDeclarationList(params: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams): any {
    this.VariableDeclaration(params);
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Comma();
      this.VariableDeclaration(params);
      return null;
    }));
    return null;
  }
  VariableDeclaration(params: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_VariableDeclaration(params);
    }), "VariableDeclaration", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_VariableDeclaration(params: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams): any {
    this.Or(__qin_java_functional(() => {
      this.BindingIdentifier(params);
      this.Option(__qin_java_functional(() => {
      return this.Initializer(params);
    }));
      return null;
    }), __qin_java_functional(() => {
      this.BindingPattern(params);
      this.Initializer(params);
      return null;
    }));
    return null;
  }
  EmptyStatement(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_EmptyStatement();
    }), "EmptyStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_EmptyStatement(): any {
    this.__qin_field_tokenConsumer.Semicolon();
    return null;
  }
  ExpressionStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ExpressionStatement(params);
    }), "ExpressionStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ExpressionStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.assertLookaheadNotIn(["LBrace", "Function", "Class"]);
    this.assertNotContextualSequenceNoLT("async", "Function");
    this.assertNotContextualSequence("let", "LBracket");
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.debugLog(__qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", "ExpressionStatement after Expression: parseSuccess=", this.__qin_field_parseSuccess), ", curToken="), this.LA(1.0)), ", index="), this.__qin_field_currentIndex));
    this.SemicolonASI();
    return null;
  }
  IfStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_IfStatement(params);
    }), "IfStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_IfStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.If();
      this.__qin_field_tokenConsumer.LParen();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.__qin_field_tokenConsumer.RParen();
      this.IfStatementBody(params);
      this.__qin_field_tokenConsumer.Else();
      this.IfStatementBody(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.If();
      this.__qin_field_tokenConsumer.LParen();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.__qin_field_tokenConsumer.RParen();
      this.IfStatementBody(params);
      this.assertLookaheadNot("Else");
      return null;
    }));
    return null;
  }
  IfStatementBody(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_IfStatementBody(params);
    }), "IfStatementBody", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_IfStatementBody(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.Statement(params);
    }), __qin_java_functional(() => {
      return this.FunctionDeclaration(new com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams(params.yield(), params.await(), false));
    }));
    return null;
  }
  BreakableStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_BreakableStatement(params);
    }), "BreakableStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_BreakableStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.IterationStatement(params);
    }), __qin_java_functional(() => {
      return this.SwitchStatement(params);
    }));
    return null;
  }
  IterationStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_IterationStatement(params);
    }), "IterationStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_IterationStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.DoWhileStatement(params);
    }), __qin_java_functional(() => {
      return this.WhileStatement(params);
    }), __qin_java_functional(() => {
      return this.ForStatement(params);
    }), __qin_java_functional(() => {
      return this.ForInOfStatement(params);
    }));
    return null;
  }
  DoWhileStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_DoWhileStatement(params);
    }), "DoWhileStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_DoWhileStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Do();
    this.Statement(params);
    this.__qin_field_tokenConsumer.While();
    this.__qin_field_tokenConsumer.LParen();
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.__qin_field_tokenConsumer.RParen();
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Semicolon();
    }));
    return null;
  }
  WhileStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_WhileStatement(params);
    }), "WhileStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_WhileStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.While();
    this.__qin_field_tokenConsumer.LParen();
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.__qin_field_tokenConsumer.RParen();
    this.Statement(params);
    return null;
  }
  ForStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ForStatement(params);
    }), "ForStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ForStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.__qin_field_tokenConsumer.LParen();
      this.__qin_field_tokenConsumer.Var();
      this.VariableDeclarationList(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(false, params.yield(), params.await()));
      this.__qin_field_tokenConsumer.Semicolon();
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.Semicolon();
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.__qin_field_tokenConsumer.LParen();
      this.LexicalDeclaration(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(false, params.yield(), params.await()));
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.Semicolon();
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.__qin_field_tokenConsumer.LParen();
      this.assertNotContextualSequence("let", "LBracket");
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(false, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.Semicolon();
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.Semicolon();
      this.Option(__qin_java_functional(() => {
      return this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }));
    return null;
  }
  ForInOfStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ForInOfStatement(params);
    }), "ForInOfStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ForInOfStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.__qin_field_tokenConsumer.LParen();
      this.__qin_field_tokenConsumer.Var();
      this.BindingIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.Initializer(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(false, params.yield(), params.await()));
      this.__qin_field_tokenConsumer.In();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Await();
    }));
      this.__qin_field_tokenConsumer.LParen();
      this.__qin_field_tokenConsumer.Var();
      this.ForBinding(params);
      this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.In();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      return null;
    }), __qin_java_functional(() => {
      this.consumeIdentifierValue("of");
      this.AssignmentExpression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      return null;
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Await();
    }));
      this.__qin_field_tokenConsumer.LParen();
      this.ForDeclaration(params);
      this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.In();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      return null;
    }), __qin_java_functional(() => {
      this.consumeIdentifierValue("of");
      this.AssignmentExpression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      return null;
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.For();
      this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Await();
    }));
      this.__qin_field_tokenConsumer.LParen();
      this.assertNotContextual("let");
      this.LeftHandSideExpression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.In();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      return null;
    }), __qin_java_functional(() => {
      this.consumeIdentifierValue("of");
      this.AssignmentExpression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      return null;
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Statement(params);
      return null;
    }));
    return null;
  }
  ForBinding(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ForBinding(params);
    }), "ForBinding", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ForBinding(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.BindingIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }), __qin_java_functional(() => {
      return this.BindingPattern(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
    return null;
  }
  SwitchStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_SwitchStatement(params);
    }), "SwitchStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_SwitchStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Switch();
    this.__qin_field_tokenConsumer.LParen();
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.__qin_field_tokenConsumer.RParen();
    this.CaseBlock(params);
    return null;
  }
  CaseBlock(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_CaseBlock(params);
    }), "CaseBlock", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_CaseBlock(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.LBrace();
      this.Option(__qin_java_functional(() => {
      return this.CaseClauses(params);
    }));
      this.DefaultClause(params);
      this.Option(__qin_java_functional(() => {
      return this.CaseClauses(params);
    }));
      this.__qin_field_tokenConsumer.RBrace();
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.LBrace();
      this.Option(__qin_java_functional(() => {
      return this.CaseClauses(params);
    }));
      this.__qin_field_tokenConsumer.RBrace();
      return null;
    }));
    return null;
  }
  CaseClauses(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_CaseClauses(params);
    }), "CaseClauses", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_CaseClauses(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.CaseClause(params);
    this.Many(__qin_java_functional(() => {
      return this.CaseClause(params);
    }));
    return null;
  }
  CaseClause(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_CaseClause(params);
    }), "CaseClause", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_CaseClause(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Case();
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.__qin_field_tokenConsumer.Colon();
    this.Option(__qin_java_functional(() => {
      return this.StatementList(params);
    }));
    return null;
  }
  DefaultClause(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_DefaultClause(params);
    }), "DefaultClause", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_DefaultClause(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Default();
    this.__qin_field_tokenConsumer.Colon();
    this.Option(__qin_java_functional(() => {
      return this.StatementList(params);
    }));
    return null;
  }
  ContinueStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ContinueStatement(params);
    }), "ContinueStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ContinueStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Continue();
      this.assertNoLineBreak();
      this.LabelIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.SemicolonASI();
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Continue();
      this.SemicolonASI();
      return null;
    }));
    return null;
  }
  BreakStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_BreakStatement(params);
    }), "BreakStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_BreakStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Break();
      this.assertNoLineBreak();
      this.LabelIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.SemicolonASI();
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Break();
      this.SemicolonASI();
      return null;
    }));
    return null;
  }
  ReturnStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ReturnStatement(params);
    }), "ReturnStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ReturnStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Return();
      this.assertNoLineBreak();
      this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
      this.SemicolonASI();
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Return();
      this.SemicolonASI();
      return null;
    }));
    return null;
  }
  WithStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_WithStatement(params);
    }), "WithStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_WithStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.With();
    this.__qin_field_tokenConsumer.LParen();
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.__qin_field_tokenConsumer.RParen();
    this.Statement(params);
    return null;
  }
  LabelledStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_LabelledStatement(params);
    }), "LabelledStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_LabelledStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.LabelIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.__qin_field_tokenConsumer.Colon();
    this.LabelledItem(params);
    return null;
  }
  LabelledItem(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_LabelledItem(params);
    }), "LabelledItem", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_LabelledItem(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.Statement(params);
    }), __qin_java_functional(() => {
      return this.FunctionDeclaration(new com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams(params.yield(), params.await(), false));
    }));
    return null;
  }
  ThrowStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_ThrowStatement(params);
    }), "ThrowStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_ThrowStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Throw();
    this.assertNoLineBreak();
    this.Expression(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    this.debugLog(__qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", "ExpressionStatement after Expression: parseSuccess=", this.__qin_field_parseSuccess), ", curToken="), this.LA(1.0)), ", index="), this.__qin_field_currentIndex));
    this.SemicolonASI();
    return null;
  }
  TryStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TryStatement(params);
    }), "TryStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_TryStatement(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Try();
      this.Block(params);
      this.Catch(params);
      this.Finally(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Try();
      this.Block(params);
      this.Catch(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Try();
      this.Block(params);
      this.Finally(params);
      return null;
    }));
    return null;
  }
  Catch(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_Catch(params);
    }), "Catch", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_Catch(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Catch();
      this.__qin_field_tokenConsumer.LParen();
      this.CatchParameter(params);
      this.__qin_field_tokenConsumer.RParen();
      this.Block(params);
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Catch();
      this.Block(params);
      return null;
    }));
    return null;
  }
  CatchParameter(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_CatchParameter(params);
    }), "CatchParameter", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_CatchParameter(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.Or(__qin_java_functional(() => {
      return this.BindingIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }), __qin_java_functional(() => {
      return this.BindingPattern(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, params.yield(), params.await()));
    }));
    return null;
  }
  Finally(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_Finally(params);
    }), "Finally", "SlimeStatementParser", __qin_subhuti_rule_cache_key([params]));
  }
  __qin_subhuti_raw_Finally(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    this.__qin_field_tokenConsumer.Finally();
    this.Block(params);
    return null;
  }
  DebuggerStatement(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_DebuggerStatement();
    }), "DebuggerStatement", "SlimeStatementParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_DebuggerStatement(): any {
    this.__qin_field_tokenConsumer.Debugger();
    this.SemicolonASI();
    return null;
  }
  SemicolonASI(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_SemicolonASI();
    }), "SemicolonASI", "SlimeStatementParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_SemicolonASI(): any {
    let t1: any = this.LA(1.0);
    if ((() => {
      if (__qin_binary__("!=", t1, null)) {
        return __QinJavaLangString.equals("Semicolon", t1.tokenName());
      }
      return false;
    })()) {
      this.__qin_field_tokenConsumer.Semicolon();
      return null;
    }
    if ((() => {
      if (this.canAutoInsertSemicolon()) {
        return false;
      }
      return true;
    })()) {
      let curToken: any = this.LA(1.0);
      this.debugLog(__qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", __qin_binary__("+", "SemicolonASI fail: curToken=", curToken), ", lineBreakBefore="), (() => {
      if (__qin_binary__("!=", curToken, null)) {
        return curToken.hasLineBreakBefore();
      }
      return false;
    })()), ", index="), this.__qin_field_currentIndex));
      this.setParseFail();
      return null;
    }
    this.setParseSuccess();
    return null;
  }
  canAutoInsertSemicolon(): any {
    if (this.isEof()) {
      return true;
    }
    let curToken: any = this.LA(1.0);
    if (__qin_binary__("==", curToken, null)) {
      return true;
    }
    if (curToken.hasLineBreakBefore()) {
      return true;
    }
    let nextIndex: any = curToken.index();
    if ((() => {
      if (__qin_binary__("!=", nextIndex, null)) {
        return __qin_binary__(">", nextIndex, this.__qin_field_currentIndex);
      }
      return false;
    })()) {
      if (this.hasLineTerminatorBetween(this.__qin_field_currentIndex, nextIndex)) {
        return true;
      }
    }
    if (__QinJavaLangString.equals("RBrace", curToken.tokenName())) {
      return true;
    }
    return false;
  }
  hasLineTerminatorBetween(start: number, end: number): any {
    if ((() => {
      if ((() => {
      if (__qin_binary__("<", start, 0.0)) {
        return true;
      }
      return __qin_binary__(">", end, __QinJavaLangString.length(this.__qin_field_sourceCode));
    })()) {
        return true;
      }
      return __qin_binary__(">=", start, end);
    })()) {
      return false;
    }
    for (let i: any = start; __qin_binary__("<", i, end); i = __qin_binary__("+", i, 1.0)) {
      let ch: any = __QinJavaLangString.charAt(this.__qin_field_sourceCode, i);
      if ((() => {
      if ((() => {
      if ((() => {
      if (__qin_binary__("==", ch, "\n")) {
        return true;
      }
      return __qin_binary__("==", ch, "\r");
    })()) {
        return true;
      }
      return __qin_binary__("==", ch, " ");
    })()) {
        return true;
      }
      return __qin_binary__("==", ch, " ");
    })()) {
        return true;
      }
    }
    return false;
  }
  Declaration(params: com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams): any {
    return null;
  }
  LexicalDeclaration(params: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams): any {
    return null;
  }
  ForDeclaration(params: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams): any {
    return null;
  }
  BindingRestElement(): any {
    return null;
  }
  BindingElement(): any {
    return null;
  }
  FunctionDeclaration(params: com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams): any {
    return null;
  }
}
const SlimeStatementParser = com_slime_parser_statements_SlimeStatementParser;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_slime_parser_statements_SlimeStatementParser };
