// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __qin_java_string_hash_code__, __qin_java_identity_hash_code__, __qin_java_value_hash_code__, __qin_java_values_equal__, __qin_java_hash_key__, __qin_java_hash_key_equals__, __QinJavaUtilRegexPattern } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
const Pattern = __QinJavaUtilRegexPattern;
class com_subhuti_struct_SubhutiTokenLookahead {
  __qin_field_is: any = null as any;
  __qin_field_not: any = null as any;
  __qin_field___qin_in: any = null as any;
  __qin_field_notIn: any = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 4: {
        const is: any = __qin_args[0];
        const not: any = __qin_args[1];
        const __qin_in: any = __qin_args[2];
        const notIn: any = __qin_args[3];
        this.__qin_constructor_com_subhuti_struct_SubhutiTokenLookahead_4(is, not, __qin_in, notIn);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SubhutiTokenLookahead/" + __qin_args.length);
    }
  }
  __qin_constructor_com_subhuti_struct_SubhutiTokenLookahead_4(is: any, not: any, __qin_in: any, notIn: any): void {
    this.__qin_field_is = null;
    this.__qin_field_not = null;
    this.__qin_field___qin_in = null;
    this.__qin_field_notIn = null;
    (() => {
      this.__qin_field_is = is;
      this.__qin_field_not = not;
      this.__qin_field___qin_in = __qin_in;
      this.__qin_field_notIn = notIn;
      return null;
    })();
  }
  hasConstraints(): any {
    return (() => {
      if ((() => {
      if ((() => {
      if (__qin_binary__("!=", this.__qin_field_is, null)) {
        return true;
      }
      return __qin_binary__("!=", this.__qin_field_not, null);
    })()) {
        return true;
      }
      return (() => {
      if (__qin_binary__("!=", this.__qin_field___qin_in, null)) {
        return (() => {
      if (__QinJavaLangString.isEmpty(this.__qin_field___qin_in)) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })();
    })()) {
        return true;
      }
      return (() => {
      if (__qin_binary__("!=", this.__qin_field_notIn, null)) {
        return (() => {
      if (__QinJavaLangString.isEmpty(this.__qin_field_notIn)) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })();
    })();
  }
  static builder(): any {
    return new com_subhuti_struct_SubhutiTokenLookahead$Builder();
  }
  is(): any {
    return this.__qin_field_is;
  }
  not(): any {
    return this.__qin_field_not;
  }
  in(): any {
    return this.__qin_field___qin_in;
  }
  notIn(): any {
    return this.__qin_field_notIn;
  }
  equals(other) {
    if (this === other) return true;
    if (!(other instanceof com_subhuti_struct_SubhutiTokenLookahead)) return false;
    return __qin_java_values_equal__(this.__qin_field_is, other.__qin_field_is)
      && __qin_java_values_equal__(this.__qin_field_not, other.__qin_field_not)
      && __qin_java_values_equal__(this.__qin_field___qin_in, other.__qin_field___qin_in)
      && __qin_java_values_equal__(this.__qin_field_notIn, other.__qin_field_notIn);
  }
  hashCode() {
    let result = 1;
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_is);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_not);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_in);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_notIn);
    return result;
  }
  toString() {
    return "SubhutiTokenLookahead[" + "is=" + this.__qin_field_is + ", " + "not=" + this.__qin_field_not + ", " + "in=" + this.__qin_field___qin_in + ", " + "notIn=" + this.__qin_field_notIn + "]";
  }
}
const SubhutiTokenLookahead = com_subhuti_struct_SubhutiTokenLookahead;
class com_subhuti_struct_SubhutiTokenLookahead$Builder {
  __qin_field_is: any = null as any;
  __qin_field_not: any = null as any;
  __qin_field___qin_in: any = null as any;
  __qin_field_notIn: any = null as any;
  constructor(...__qin_args: any[]) {
    if (__qin_args.length !== 0) {
      throw new Error("Unsupported Java constructor arity: SubhutiTokenLookahead$Builder/" + __qin_args.length);
    }
    this.__qin_field_is = null;
    this.__qin_field_not = null;
    this.__qin_field___qin_in = null;
    this.__qin_field_notIn = null;
  }
  is(...__qin_args: any[]): any {
    if (__qin_args.length === 1 && (__qin_args[0] === null || typeof __qin_args[0] === "string")) return this.__qin_overload_is_1_0(...__qin_args);
    if (__qin_args.length === 1 && (__qin_args[0] === null || __qin_args[0] instanceof __QinJavaUtilRegexPattern)) return this.__qin_overload_is_1_1(...__qin_args);
    throw new Error("Unsupported Java overload: is/" + __qin_args.length);
  }
  __qin_overload_is_1_0(regex: string): any {
    this.__qin_field_is = __QinJavaUtilRegexPattern.compile(regex);
    return this;
  }
  __qin_overload_is_1_1(pattern: any): any {
    this.__qin_field_is = pattern;
    return this;
  }
  not(...__qin_args: any[]): any {
    if (__qin_args.length === 1 && (__qin_args[0] === null || typeof __qin_args[0] === "string")) return this.__qin_overload_not_1_0(...__qin_args);
    if (__qin_args.length === 1 && (__qin_args[0] === null || __qin_args[0] instanceof __QinJavaUtilRegexPattern)) return this.__qin_overload_not_1_1(...__qin_args);
    throw new Error("Unsupported Java overload: not/" + __qin_args.length);
  }
  __qin_overload_not_1_0(regex: string): any {
    this.__qin_field_not = __QinJavaUtilRegexPattern.compile(regex);
    return this;
  }
  __qin_overload_not_1_1(pattern: any): any {
    this.__qin_field_not = pattern;
    return this;
  }
  in(patterns: any): any {
    this.__qin_field___qin_in = patterns;
    return this;
  }
  notIn(patterns: any): any {
    this.__qin_field_notIn = patterns;
    return this;
  }
  build(): any {
    return new com_subhuti_struct_SubhutiTokenLookahead(this.__qin_field_is, this.__qin_field_not, this.__qin_field___qin_in, this.__qin_field_notIn);
  }
}
const SubhutiTokenLookahead$Builder = com_subhuti_struct_SubhutiTokenLookahead$Builder;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_subhuti_struct_SubhutiTokenLookahead, com_subhuti_struct_SubhutiTokenLookahead$Builder };
