package com.qin.debug;

import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.openapi.vfs.VirtualFileManager;
import com.intellij.openapi.vfs.newvfs.BulkFileListener;
import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
import com.intellij.util.messages.MessageBusConnection;
import org.jetbrains.annotations.NotNull;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

import static com.qin.constants.QinConstants.CMD_FLAG;
import static com.qin.constants.QinConstants.CMD_PREFIX;
import static com.qin.constants.QinConstants.CONFIG_FILE;
import static com.qin.constants.QinConstants.QIN_CMD;
import static com.qin.debug.QinConstants.AUTO_COMPILE_DEBOUNCE_MS;

/**
 * Watches workspace files that affect Qin project structure and compilation.
 */
public class QinConfigWatcher {

    private final Project project;
    private final String basePath;
    private final QinProjectSync projectSync;
    private MessageBusConnection connection;

    private volatile boolean syncing = false;
    private final ScheduledExecutorService compileScheduler = Executors.newSingleThreadScheduledExecutor();
    private ScheduledFuture<?> pendingCompileTask;
    private volatile boolean compiling = false;

    public QinConfigWatcher(Project project) {
        this.project = project;
        this.basePath = project.getBasePath();
        this.projectSync = new QinProjectSync(project);
    }

    public void setSyncing(boolean syncing) {
        this.syncing = syncing;
    }

    public void startWatching() {
        if (basePath == null) {
            return;
        }

        connection = project.getMessageBus().connect();
        connection.subscribe(VirtualFileManager.VFS_CHANGES, new BulkFileListener() {
            @Override
            public void after(@NotNull List<? extends VFileEvent> events) {
                if (syncing) {
                    return;
                }

                for (VFileEvent event : events) {
                    VirtualFile file = event.getFile();
                    if (file == null) {
                        continue;
                    }

                    String fileName = file.getName();
                    String filePath = file.getPath();
                    if (!filePath.startsWith(basePath.replace('\\', '/'))) {
                        continue;
                    }

                    if (fileName.equals(CONFIG_FILE)) {
                        QinLogger.info("[Watcher] Detected qin.config.json change: " + filePath);
                        onWorkspaceConfigChanged();
                    } else if (fileName.endsWith(".iml")) {
                        QinLogger.info("[Watcher] Detected .iml change (possibly generated by sync): " + filePath);
                        onImlChanged(file);
                    } else if (fileName.endsWith(".java") && !compiling) {
                        QinLogger.info("[Watcher] Detected Java file change: " + filePath);
                        scheduleAutoCompile(file);
                    }
                }
            }
        });

        QinLogger.info("[Watcher] Config file watcher started");
    }

    public void stopWatching() {
        if (connection != null) {
            connection.disconnect();
            connection = null;
            QinLogger.info("[Watcher] Config file watcher stopped");
        }
        compileScheduler.shutdownNow();
    }

    private void scheduleAutoCompile(VirtualFile javaFile) {
        if (pendingCompileTask != null && !pendingCompileTask.isDone()) {
            pendingCompileTask.cancel(false);
        }

        VirtualFile projectDir = findQinProject(javaFile);
        if (projectDir == null) {
            return;
        }

        Path projectPath = Paths.get(projectDir.getPath());
        pendingCompileTask = compileScheduler.schedule(
                () -> executeAutoCompile(projectPath),
                AUTO_COMPILE_DEBOUNCE_MS,
                TimeUnit.MILLISECONDS);
    }

    private VirtualFile findQinProject(VirtualFile file) {
        VirtualFile dir = file.getParent();
        while (dir != null) {
            VirtualFile configFile = dir.findChild(CONFIG_FILE);
            if (configFile != null && configFile.exists()) {
                return dir;
            }
            dir = dir.getParent();
        }
        return null;
    }

    private void executeAutoCompile(Path projectPath) {
        try {
            compiling = true;
            QinLogger.info("[AutoCompile] Starting compile for project: " + projectPath.getFileName());

            ProcessBuilder pb = new ProcessBuilder(CMD_PREFIX, CMD_FLAG, QIN_CMD, "compile");
            pb.directory(projectPath.toFile());
            pb.redirectErrorStream(true);

            Process process = pb.start();
            try (java.io.BufferedReader reader = new java.io.BufferedReader(
                    new java.io.InputStreamReader(process.getInputStream(), java.nio.charset.StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    QinLogger.info("[AutoCompile] " + line);
                }
            }

            int exitCode = process.waitFor();
            if (exitCode == 0) {
                QinLogger.info("[AutoCompile] Compile succeeded");
            } else {
                QinLogger.error("[AutoCompile] Compile command failed with exit code: " + exitCode);
            }

            projectSync.refreshProject();
        } catch (Exception e) {
            QinLogger.error("[AutoCompile] Compile execution failed: " + e.getMessage());
        } finally {
            compiling = false;
        }
    }

    private void onWorkspaceConfigChanged() {
        ApplicationManager.getApplication().executeOnPooledThread(() -> {
            try {
                syncing = true;
                projectSync.syncAllProjects(false);
            } finally {
                syncing = false;
            }
        });
    }

    private void onImlChanged(VirtualFile imlFile) {
        try {
            String content = new String(imlFile.contentsToByteArray(), java.nio.charset.StandardCharsets.UTF_8);
            int idx = content.indexOf("LANGUAGE_LEVEL=\"");
            if (idx < 0) {
                return;
            }

            int start = idx + "LANGUAGE_LEVEL=\"".length();
            int end = content.indexOf("\"", start);
            if (end < 0) {
                return;
            }

            String languageLevel = content.substring(start, end);
            String version = languageLevel.replace("JDK_", "").replace("_", ".");
            QinConfig tempConfig = new QinConfig(version);

            QinLogger.info("[Watcher] Detected LANGUAGE_LEVEL in .iml: " + languageLevel);
            projectSync.refreshLanguageLevel(tempConfig);
        } catch (Exception e) {
            QinLogger.error("[Watcher] Failed to process .iml change: " + e.getMessage());
        }
    }
}
