package com.qin.debug;

import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.openapi.vfs.VirtualFileManager;
import com.intellij.openapi.vfs.newvfs.BulkFileListener;
import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
import com.intellij.util.messages.MessageBusConnection;
import org.jetbrains.annotations.NotNull;

import java.util.List;

import static com.qin.constants.QinConstants.CONFIG_FILE;

/**
 * Watches workspace files that affect Qin project structure and compilation.
 */
public class QinConfigWatcher {

    private final Project project;
    private final String basePath;
    private final QinProjectSync projectSync;
    private MessageBusConnection connection;

    private volatile boolean syncing = false;

    public QinConfigWatcher(Project project) {
        this.project = project;
        this.basePath = project.getBasePath();
        this.projectSync = new QinProjectSync(project);
    }

    public void setSyncing(boolean syncing) {
        this.syncing = syncing;
    }

    public void startWatching() {
        if (basePath == null) {
            return;
        }

        connection = project.getMessageBus().connect();
        connection.subscribe(VirtualFileManager.VFS_CHANGES, new BulkFileListener() {
            @Override
            public void after(@NotNull List<? extends VFileEvent> events) {
                if (syncing) {
                    return;
                }

                for (VFileEvent event : events) {
                    VirtualFile file = event.getFile();
                    if (file == null) {
                        continue;
                    }

                    String fileName = file.getName();
                    String filePath = file.getPath();
                    if (!filePath.startsWith(basePath.replace('\\', '/'))) {
                        continue;
                    }

                    if (fileName.equals(CONFIG_FILE)) {
                        QinLogger.info("[Watcher] Detected qin.config.json change: " + filePath);
                        onWorkspaceConfigChanged();
                    } else if (fileName.endsWith(".iml")) {
                        QinLogger.info("[Watcher] Detected .iml change (possibly generated by sync): " + filePath);
                        onImlChanged(file);
                    }
                }
            }
        });

        QinLogger.info("[Watcher] Config file watcher started");
    }

    public void stopWatching() {
        if (connection != null) {
            connection.disconnect();
            connection = null;
            QinLogger.info("[Watcher] Config file watcher stopped");
        }
    }

    private void onWorkspaceConfigChanged() {
        ApplicationManager.getApplication().executeOnPooledThread(() -> {
            try {
                syncing = true;
                projectSync.syncAllProjects(false);
            } finally {
                syncing = false;
            }
        });
    }

    private void onImlChanged(VirtualFile imlFile) {
        try {
            String content = new String(imlFile.contentsToByteArray(), java.nio.charset.StandardCharsets.UTF_8);
            int idx = content.indexOf("LANGUAGE_LEVEL=\"");
            if (idx < 0) {
                return;
            }

            int start = idx + "LANGUAGE_LEVEL=\"".length();
            int end = content.indexOf("\"", start);
            if (end < 0) {
                return;
            }

            String languageLevel = content.substring(start, end);
            String version = languageLevel.replace("JDK_", "").replace("_", ".");
            QinConfig tempConfig = new QinConfig(version);

            QinLogger.info("[Watcher] Detected LANGUAGE_LEVEL in .iml: " + languageLevel);
            projectSync.refreshLanguageLevel(tempConfig);
        } catch (Exception e) {
            QinLogger.error("[Watcher] Failed to process .iml change: " + e.getMessage());
        }
    }
}
