import { com_slime_parser_consumer_SlimeTokenConsumer } from "../consumer/SlimeTokenConsumer.ts";
import { com_slime_token_JavaScriptTokens } from "../../token/JavaScriptTokens.ts";
import { com_subhuti_parser_SubhutiParser } from "../../../subhuti/parser/SubhutiParser.ts";
import { com_subhuti_struct_SubhutiCreateToken, com_subhuti_struct_SubhutiCreateToken$Builder } from "../../../subhuti/struct/SubhutiCreateToken.ts";
import { com_subhuti_struct_SubhutiCst, com_subhuti_struct_SubhutiCst$Builder } from "../../../subhuti/struct/SubhutiCst.ts";
import { com_subhuti_struct_SubhutiMatchToken, com_subhuti_struct_SubhutiMatchToken$Builder } from "../../../subhuti/struct/SubhutiMatchToken.ts";
import { com_subhuti_parser_SubhutiParserFinal } from "../../../subhuti/parser/SubhutiParserFinal.ts";
import { com_subhuti_parser_SubhutiParserCombinators, com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher, com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext, com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext, com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame } from "../../../subhuti/parser/SubhutiParserCombinators.ts";
import { com_subhuti_parser_SubhutiParserCore, com_subhuti_parser_SubhutiParserCore$RuleExecutionResult } from "../../../subhuti/parser/SubhutiParserCore.ts";
import { com_subhuti_parser_SubhutiParserState } from "../../../subhuti/parser/SubhutiParserState.ts";
import { com_subhuti_lookahead_SubhutiTokenLookahead } from "../../../subhuti/lookahead/SubhutiTokenLookahead.ts";
const SlimeTokenConsumer = com_slime_parser_consumer_SlimeTokenConsumer;
const JavaScriptTokens = com_slime_token_JavaScriptTokens;
const SubhutiParser = com_subhuti_parser_SubhutiParser;
const SubhutiCreateToken = com_subhuti_struct_SubhutiCreateToken;
const SubhutiCst = com_subhuti_struct_SubhutiCst;
const SubhutiMatchToken = com_subhuti_struct_SubhutiMatchToken;
const SubhutiParserFinal = com_subhuti_parser_SubhutiParserFinal;
const SubhutiParserCombinators = com_subhuti_parser_SubhutiParserCombinators;
const StopTokenMatcher = com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher;
const AllowErrorOrBranchContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext;
const AllowErrorContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext;
const ManyTolerantFrame = com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame;
const SubhutiParserCore = com_subhuti_parser_SubhutiParserCore;
const RuleExecutionResult = com_subhuti_parser_SubhutiParserCore$RuleExecutionResult;
const SubhutiParserState = com_subhuti_parser_SubhutiParserState;

// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__, __QinJavaLangThrowable, __QinJavaLangException, __QinJavaLangRuntimeException, __QinJavaLangReflectiveOperationException, __QinJavaLangClassNotFoundException, __QinJavaLangNoSuchMethodException, __QinJavaLangError, __QinJavaLangStackOverflowError, __QinJavaLangIllegalArgumentException, __QinJavaLangNumberFormatException, __QinJavaLangIllegalStateException, __QinJavaLangUnsupportedOperationException, __QinJavaIoIOException, __QinJavaLangStringBuilder, __QinJavaLangInteger, __qin_java_string_hash_code__, __qin_java_identity_hash_code__, __qin_java_value_hash_code__, __qin_java_values_equal__, __qin_java_hash_key__, __qin_java_hash_key_equals__, __QinJavaUtilSet, __QinJavaUtilUnmodifiableSet } from "@qin/java-sdk-js";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
const Set = __QinJavaUtilSet;
const RuntimeException = __QinJavaLangRuntimeException;
const StringBuilder = __QinJavaLangStringBuilder;
const Integer = __QinJavaLangInteger;
const NumberFormatException = __QinJavaLangNumberFormatException;
class com_slime_parser_base_SlimeJavascriptParserBase extends com_subhuti_parser_SubhutiParser {
  static __qin_field_RESERVED_WORDS: any = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 1: {
        const sourceCode: any = __qin_args[0];
        super(sourceCode, ({ getName() { return "com.slime.parser.consumer.SlimeTokenConsumer"; }, getSimpleName() { return "SlimeTokenConsumer"; }, getDeclaredConstructor(...__qin_types) { const __qin_ctor = com_slime_parser_consumer_SlimeTokenConsumer; return { newInstance(...__qin_args) { return new __qin_ctor(...__qin_args); } }; }, getConstructor(...__qin_types) { return this.getDeclaredConstructor(...__qin_types); }, equals(other) { return other != null && typeof other.getName === "function" && other.getName() === "com.slime.parser.consumer.SlimeTokenConsumer"; }, hashCode() { return -652635741; }, toString() { return "class com.slime.parser.consumer.SlimeTokenConsumer"; } }), com_slime_token_JavaScriptTokens.getTokens());
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase_1(sourceCode);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeJavascriptParserBase/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase_1(sourceCode: string): void {
    null;
  }
  isReservedWord(identifier: string): any {
    return __QinJavaLangString.contains(com_slime_parser_base_SlimeJavascriptParserBase.__qin_field_RESERVED_WORDS, identifier);
  }
  token(tokenName: string): any {
    return this._consumeToken(tokenName, this.__qin_field_currentMode);
  }
  consumeIdentifierValue(value: string): any {
    let cur: any = this.LA(1.0);
    if ((() => {
      if ((() => {
      if (__qin_binary__("!=", cur, null)) {
        return __QinJavaLangString.equals("IdentifierName", cur.tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(value, cur.value());
      }
      return false;
    })()) {
      this._consumeToken("IdentifierName", this.__qin_field_currentMode);
      return true;
    }
    this.setParseFail();
    return false;
  }
  match(tokenName: string): any {
    return (() => {
      if (__qin_binary__("!=", this.LA(1.0), null)) {
        return __QinJavaLangString.equals(this.LA(1.0).tokenName(), tokenName);
      }
      return false;
    })();
  }
  matchIdentifierValue(...__qin_args: any[]): any {
    if (__qin_args.length === 1 && (__qin_args[0] === null || typeof __qin_args[0] === "string")) return this.__qin_overload_matchIdentifierValue_1_0(...__qin_args);
    if (__qin_args.length === 2 && (__qin_args[0] === null || typeof __qin_args[0] === "string") && typeof __qin_args[1] === "number") return this.__qin_overload_matchIdentifierValue_2_1(...__qin_args);
    throw new Error("Unsupported Java overload: matchIdentifierValue/" + __qin_args.length);
  }
  __qin_overload_matchIdentifierValue_1_0(value: string): any {
    return this.matchIdentifierValue(value, 1.0);
  }
  __qin_overload_matchIdentifierValue_2_1(value: string, offset: number): any {
    return (() => {
      if ((() => {
      if (__qin_binary__("!=", this.LA(offset), null)) {
        return __QinJavaLangString.equals("IdentifierName", this.LA(offset).tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(value, this.LA(offset).value());
      }
      return false;
    })();
  }
  canStartArrowFunctionHead(): any {
    let first: any = this.safeLookahead(1.0);
    if (__qin_binary__("==", first, null)) {
      return false;
    }
    if ((() => {
      if ((() => {
      if (__QinJavaLangString.equals("IdentifierName", first.tokenName())) {
        return true;
      }
      return __QinJavaLangString.equals("Yield", first.tokenName());
    })()) {
        return true;
      }
      return __QinJavaLangString.equals("Await", first.tokenName());
    })()) {
      if ((() => {
      if (__QinJavaLangString.equals("IdentifierName", first.tokenName())) {
        return (() => {
      if (__qin_binary__("==", first.value(), null)) {
        return true;
      }
      return this.isReservedWord(first.value());
    })();
      }
      return false;
    })()) {
        return false;
      }
      let second: any = this.safeLookahead(2.0);
      if ((() => {
      if (__qin_binary__("==", second, null)) {
        return true;
      }
      return second.hasLineBreakBefore();
    })()) {
        return false;
      }
      let tokenName: any = second.tokenName();
      return (() => {
      if ((() => {
      if (__QinJavaLangString.equals("Arrow", tokenName)) {
        return true;
      }
      return __QinJavaLangString.equals("Question", tokenName);
    })()) {
        return true;
      }
      return __QinJavaLangString.equals("Colon", tokenName);
    })();
    }
    if (__QinJavaLangString.equals("LParen", first.tokenName())) {
      return this.hasArrowAfterBalancedParens(1.0);
    }
    return false;
  }
  canStartAsyncArrowFunctionHead(): any {
    if ((() => {
      if (this.matchIdentifierValue("async")) {
        return false;
      }
      return true;
    })()) {
      return false;
    }
    let second: any = this.safeLookahead(2.0);
    if ((() => {
      if (__qin_binary__("==", second, null)) {
        return true;
      }
      return second.hasLineBreakBefore();
    })()) {
      return false;
    }
    if (__QinJavaLangString.equals("IdentifierName", second.tokenName())) {
      return true;
    }
    if (__QinJavaLangString.equals("LParen", second.tokenName())) {
      return this.hasArrowAfterBalancedParens(2.0);
    }
    return false;
  }
  hasArrowAfterBalancedParens(lParenOffset: number): any {
    let open: any = this.safeLookahead(lParenOffset);
    if ((() => {
      if (__qin_binary__("==", open, null)) {
        return true;
      }
      return (() => {
      if (__QinJavaLangString.equals("LParen", open.tokenName())) {
        return false;
      }
      return true;
    })();
    })()) {
      return false;
    }
    let depth: any = 0.0;
    let seenClosingParen: any = false;
    for (let offset: any = lParenOffset; __qin_binary__("<=", offset, 128.0); offset = __qin_binary__("+", offset, 1.0)) {
      let token: any = this.safeLookahead(offset);
      if (__qin_binary__("==", token, null)) {
        return false;
      }
      let tokenName: any = token.tokenName();
      if (__QinJavaLangString.equals("LParen", tokenName)) {
        depth = __qin_binary__("+", depth, 1.0);
        continue;
      }
      if (__QinJavaLangString.equals("RParen", tokenName)) {
        depth = __qin_binary__("-", depth, 1.0);
        if (__qin_binary__("==", depth, 0.0)) {
          seenClosingParen = true;
        }
        if (__qin_binary__("<", depth, 0.0)) {
          return false;
        }
        continue;
      }
      if ((() => {
      if (seenClosingParen) {
        return false;
      }
      return true;
    })()) {
        continue;
      }
      if (__QinJavaLangString.equals("Arrow", tokenName)) {
        return (() => {
      if (token.hasLineBreakBefore()) {
        return false;
      }
      return true;
    })();
      }
      if ((() => {
      if ((() => {
      if ((() => {
      if (__QinJavaLangString.equals("Semicolon", tokenName)) {
        return true;
      }
      return __QinJavaLangString.equals("Comma", tokenName);
    })()) {
        return true;
      }
      return __QinJavaLangString.equals("Assign", tokenName);
    })()) {
        return true;
      }
      return __QinJavaLangString.equals("RBrace", tokenName);
    })()) {
        return false;
      }
    }
    return false;
  }
  safeLookahead(offset: number): any {
    try {
      return this.LA(offset);
    } catch (e) {
      if (!(e instanceof __QinJavaLangRuntimeException)) {
        throw e;
      }
      return null;
    }
    return null;
  }
  curToken(): any {
    return this.LA(1.0);
  }
  isValidIdentifierWithEscapes(value: string): any {
    return (() => {
      if (__qin_binary__("!=", value, null)) {
        return (() => {
      if (__QinJavaLangString.isEmpty(value)) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })();
  }
  decodeIdentifier(value: string): any {
    if (__qin_binary__("==", value, null)) {
      return null;
    }
    let result: any = new __QinJavaLangStringBuilder();
    let i: any = 0.0;
    while (__qin_binary__("<", i, __QinJavaLangString.length(value))) {
      if ((() => {
      if ((() => {
      if (__qin_binary__("<", __qin_binary__("+", i, 1.0), __QinJavaLangString.length(value))) {
        return __qin_binary__("==", __QinJavaLangString.charAt(value, i), "\\");
      }
      return false;
    })()) {
        return __qin_binary__("==", __QinJavaLangString.charAt(value, __qin_binary__("+", i, 1.0)), "u");
      }
      return false;
    })()) {
        if ((() => {
      if (__qin_binary__("<", __qin_binary__("+", i, 2.0), __QinJavaLangString.length(value))) {
        return __qin_binary__("==", __QinJavaLangString.charAt(value, __qin_binary__("+", i, 2.0)), "{");
      }
      return false;
    })()) {
          let endBrace: any = value.indexOf("}", __qin_binary__("+", i, 3.0));
          if (__qin_binary__("==", endBrace, __qin_binary__("-", 0.0, 1.0))) {
            return null;
          }
          let hex: any = __QinJavaLangString.substring(value, __qin_binary__("+", i, 3.0), endBrace);
          try {
            let codePoint: any = __QinJavaLangInteger.parseInt(hex, 16.0);
            result.appendCodePoint(codePoint);
          } catch (e) {
            if (!(e instanceof __QinJavaLangNumberFormatException)) {
              throw e;
            }
            return null;
          }
          i = __qin_binary__("+", endBrace, 1.0);
        } else {
          if (__qin_binary__(">", __qin_binary__("+", i, 6.0), __QinJavaLangString.length(value))) {
            return null;
          }
          let hex: any = __QinJavaLangString.substring(value, __qin_binary__("+", i, 2.0), __qin_binary__("+", i, 6.0));
          try {
            let codePoint: any = __QinJavaLangInteger.parseInt(hex, 16.0);
            result.appendCodePoint(codePoint);
          } catch (e) {
            if (!(e instanceof __QinJavaLangNumberFormatException)) {
              throw e;
            }
            return null;
          }
          i += 6.0;
        }
      } else {
        result.append(__QinJavaLangString.charAt(value, i));
        i = __qin_binary__("+", i, 1.0);
      }
    }
    return result.toString();
  }
  assertNotContextualSequence(keyword: string, nextTokenName: string): any {
    let t1: any = this.LA(1.0);
    let t2: any = this.LA(2.0);
    if ((() => {
      if ((() => {
      if ((() => {
      if ((() => {
      if (__qin_binary__("!=", t1, null)) {
        return __qin_binary__("!=", t2, null);
      }
      return false;
    })()) {
        return __QinJavaLangString.equals("IdentifierName", t1.tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(keyword, t1.value());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(nextTokenName, t2.tokenName());
      }
      return false;
    })()) {
      this.setParseFail();
    }
    return null;
  }
  assertNotContextualSequenceNoLT(keyword: string, nextTokenName: string): any {
    let t1: any = this.LA(1.0);
    let t2: any = this.LA(2.0);
    if ((() => {
      if ((() => {
      if ((() => {
      if ((() => {
      if ((() => {
      if (__qin_binary__("!=", t1, null)) {
        return __qin_binary__("!=", t2, null);
      }
      return false;
    })()) {
        return __QinJavaLangString.equals("IdentifierName", t1.tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(keyword, t1.value());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(nextTokenName, t2.tokenName());
      }
      return false;
    })()) {
        return (() => {
      if (t2.hasLineBreakBefore()) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })()) {
      this.setParseFail();
    }
    return null;
  }
  assertNotContextual(keyword: string): any {
    let t1: any = this.LA(1.0);
    if ((() => {
      if ((() => {
      if (__qin_binary__("!=", t1, null)) {
        return __QinJavaLangString.equals("IdentifierName", t1.tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(keyword, t1.value());
      }
      return false;
    })()) {
      this.setParseFail();
    }
    return null;
  }
  assertNotContextualPair(k1: string, k2: string): any {
    let t1: any = this.LA(1.0);
    let t2: any = this.LA(2.0);
    if ((() => {
      if ((() => {
      if ((() => {
      if ((() => {
      if ((() => {
      if (__qin_binary__("!=", t1, null)) {
        return __qin_binary__("!=", t2, null);
      }
      return false;
    })()) {
        return __QinJavaLangString.equals("IdentifierName", t1.tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(k1, t1.value());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals("IdentifierName", t2.tokenName());
      }
      return false;
    })()) {
        return __QinJavaLangString.equals(k2, t2.value());
      }
      return false;
    })()) {
      this.setParseFail();
    }
    return null;
  }
}
const SlimeJavascriptParserBase = com_slime_parser_base_SlimeJavascriptParserBase;
class com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams {
  __qin_field___qin_in: boolean | null = null as any;
  __qin_field___qin_yield: boolean | null = null as any;
  __qin_field___qin_await: boolean | null = null as any;
  static __qin_field_DEFAULT: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 0: {
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams_0();
        return;
      }
      case 3: {
        const __qin_in: any = __qin_args[0];
        const __qin_yield: any = __qin_args[1];
        const __qin_await: any = __qin_args[2];
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams_3(__qin_in, __qin_yield, __qin_await);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeJavascriptParserBase$ExpressionParams/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams_0(): void {
    this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams_3(true, false, false);
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams_3(__qin_in: boolean, __qin_yield: boolean, __qin_await: boolean): void {
    this.__qin_field___qin_in = null;
    this.__qin_field___qin_yield = null;
    this.__qin_field___qin_await = null;
    (() => {
      this.__qin_field___qin_in = __qin_in;
      this.__qin_field___qin_yield = __qin_yield;
      this.__qin_field___qin_await = __qin_await;
      return null;
    })();
  }
  withIn(__qin_in: boolean): any {
    return new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(__qin_in, this.__qin_field___qin_yield, this.__qin_field___qin_await);
  }
  withYield(__qin_yield: boolean): any {
    return new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(this.__qin_field___qin_in, __qin_yield, this.__qin_field___qin_await);
  }
  withAwait(__qin_await: boolean): any {
    return new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(this.__qin_field___qin_in, this.__qin_field___qin_yield, __qin_await);
  }
  in(): any {
    return this.__qin_field___qin_in;
  }
  yield(): any {
    return this.__qin_field___qin_yield;
  }
  await(): any {
    return this.__qin_field___qin_await;
  }
  equals(other) {
    if (this === other) return true;
    if (!(other instanceof com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams)) return false;
    return __qin_java_values_equal__(this.__qin_field___qin_in, other.__qin_field___qin_in)
      && __qin_java_values_equal__(this.__qin_field___qin_yield, other.__qin_field___qin_yield)
      && __qin_java_values_equal__(this.__qin_field___qin_await, other.__qin_field___qin_await);
  }
  hashCode() {
    let result = 1;
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_in);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_yield);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_await);
    return result;
  }
  toString() {
    return "SlimeJavascriptParserBase$ExpressionParams[" + "in=" + this.__qin_field___qin_in + ", " + "yield=" + this.__qin_field___qin_yield + ", " + "await=" + this.__qin_field___qin_await + "]";
  }
}
const SlimeJavascriptParserBase$ExpressionParams = com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams;
class com_slime_parser_base_SlimeJavascriptParserBase$StatementParams {
  __qin_field___qin_yield: boolean | null = null as any;
  __qin_field___qin_await: boolean | null = null as any;
  __qin_field_returnAllowed: boolean | null = null as any;
  static __qin_field_DEFAULT: com_slime_parser_base_SlimeJavascriptParserBase$StatementParams | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 0: {
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$StatementParams_0();
        return;
      }
      case 3: {
        const __qin_yield: any = __qin_args[0];
        const __qin_await: any = __qin_args[1];
        const returnAllowed: any = __qin_args[2];
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$StatementParams_3(__qin_yield, __qin_await, returnAllowed);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeJavascriptParserBase$StatementParams/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$StatementParams_0(): void {
    this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$StatementParams_3(false, false, false);
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$StatementParams_3(__qin_yield: boolean, __qin_await: boolean, returnAllowed: boolean): void {
    this.__qin_field___qin_yield = null;
    this.__qin_field___qin_await = null;
    this.__qin_field_returnAllowed = null;
    (() => {
      this.__qin_field___qin_yield = __qin_yield;
      this.__qin_field___qin_await = __qin_await;
      this.__qin_field_returnAllowed = returnAllowed;
      return null;
    })();
  }
  yield(): any {
    return this.__qin_field___qin_yield;
  }
  await(): any {
    return this.__qin_field___qin_await;
  }
  returnAllowed(): any {
    return this.__qin_field_returnAllowed;
  }
  equals(other) {
    if (this === other) return true;
    if (!(other instanceof com_slime_parser_base_SlimeJavascriptParserBase$StatementParams)) return false;
    return __qin_java_values_equal__(this.__qin_field___qin_yield, other.__qin_field___qin_yield)
      && __qin_java_values_equal__(this.__qin_field___qin_await, other.__qin_field___qin_await)
      && __qin_java_values_equal__(this.__qin_field_returnAllowed, other.__qin_field_returnAllowed);
  }
  hashCode() {
    let result = 1;
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_yield);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_await);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_returnAllowed);
    return result;
  }
  toString() {
    return "SlimeJavascriptParserBase$StatementParams[" + "yield=" + this.__qin_field___qin_yield + ", " + "await=" + this.__qin_field___qin_await + ", " + "returnAllowed=" + this.__qin_field_returnAllowed + "]";
  }
}
const SlimeJavascriptParserBase$StatementParams = com_slime_parser_base_SlimeJavascriptParserBase$StatementParams;
class com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams {
  __qin_field___qin_yield: boolean | null = null as any;
  __qin_field___qin_await: boolean | null = null as any;
  __qin_field_isDefault: boolean | null = null as any;
  static __qin_field_DEFAULT: com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 0: {
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_0();
        return;
      }
      case 2: {
        const __qin_yield: any = __qin_args[0];
        const __qin_await: any = __qin_args[1];
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_2(__qin_yield, __qin_await);
        return;
      }
      case 3: {
        const __qin_yield: any = __qin_args[0];
        const __qin_await: any = __qin_args[1];
        const isDefault: any = __qin_args[2];
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_3(__qin_yield, __qin_await, isDefault);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeJavascriptParserBase$DeclarationParams/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_0(): void {
    this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_3(false, false, false);
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_2(__qin_yield: boolean, __qin_await: boolean): void {
    this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_3(__qin_yield, __qin_await, false);
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams_3(__qin_yield: boolean, __qin_await: boolean, isDefault: boolean): void {
    this.__qin_field___qin_yield = null;
    this.__qin_field___qin_await = null;
    this.__qin_field_isDefault = null;
    (() => {
      this.__qin_field___qin_yield = __qin_yield;
      this.__qin_field___qin_await = __qin_await;
      this.__qin_field_isDefault = isDefault;
      return null;
    })();
  }
  yield(): any {
    return this.__qin_field___qin_yield;
  }
  await(): any {
    return this.__qin_field___qin_await;
  }
  isDefault(): any {
    return this.__qin_field_isDefault;
  }
  equals(other) {
    if (this === other) return true;
    if (!(other instanceof com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams)) return false;
    return __qin_java_values_equal__(this.__qin_field___qin_yield, other.__qin_field___qin_yield)
      && __qin_java_values_equal__(this.__qin_field___qin_await, other.__qin_field___qin_await)
      && __qin_java_values_equal__(this.__qin_field_isDefault, other.__qin_field_isDefault);
  }
  hashCode() {
    let result = 1;
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_yield);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_await);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_isDefault);
    return result;
  }
  toString() {
    return "SlimeJavascriptParserBase$DeclarationParams[" + "yield=" + this.__qin_field___qin_yield + ", " + "await=" + this.__qin_field___qin_await + ", " + "isDefault=" + this.__qin_field_isDefault + "]";
  }
}
const SlimeJavascriptParserBase$DeclarationParams = com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams;
class com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams {
  __qin_field___qin_in: boolean | null = null as any;
  __qin_field___qin_yield: boolean | null = null as any;
  __qin_field___qin_await: boolean | null = null as any;
  __qin_field_tagged: boolean | null = null as any;
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 0: {
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_0();
        return;
      }
      case 2: {
        const params: any = __qin_args[0];
        const tagged: any = __qin_args[1];
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_2(params, tagged);
        return;
      }
      case 4: {
        const __qin_in: any = __qin_args[0];
        const __qin_yield: any = __qin_args[1];
        const __qin_await: any = __qin_args[2];
        const tagged: any = __qin_args[3];
        this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_4(__qin_in, __qin_yield, __qin_await, tagged);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeJavascriptParserBase$TemplateLiteralParams/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_0(): void {
    this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_4(true, false, false, false);
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_2(params: com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams, tagged: boolean): void {
    this.__qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_4(params.in(), params.yield(), params.await(), tagged);
  }
  __qin_constructor_com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams_4(__qin_in: boolean, __qin_yield: boolean, __qin_await: boolean, tagged: boolean): void {
    this.__qin_field___qin_in = null;
    this.__qin_field___qin_yield = null;
    this.__qin_field___qin_await = null;
    this.__qin_field_tagged = null;
    (() => {
      this.__qin_field___qin_in = __qin_in;
      this.__qin_field___qin_yield = __qin_yield;
      this.__qin_field___qin_await = __qin_await;
      this.__qin_field_tagged = tagged;
      return null;
    })();
  }
  expressionParams(): any {
    return new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(this.__qin_field___qin_in, this.__qin_field___qin_yield, this.__qin_field___qin_await);
  }
  in(): any {
    return this.__qin_field___qin_in;
  }
  yield(): any {
    return this.__qin_field___qin_yield;
  }
  await(): any {
    return this.__qin_field___qin_await;
  }
  tagged(): any {
    return this.__qin_field_tagged;
  }
  equals(other) {
    if (this === other) return true;
    if (!(other instanceof com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams)) return false;
    return __qin_java_values_equal__(this.__qin_field___qin_in, other.__qin_field___qin_in)
      && __qin_java_values_equal__(this.__qin_field___qin_yield, other.__qin_field___qin_yield)
      && __qin_java_values_equal__(this.__qin_field___qin_await, other.__qin_field___qin_await)
      && __qin_java_values_equal__(this.__qin_field_tagged, other.__qin_field_tagged);
  }
  hashCode() {
    let result = 1;
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_in);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_yield);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field___qin_await);
    result = result * 31 + __qin_java_value_hash_code__(this.__qin_field_tagged);
    return result;
  }
  toString() {
    return "SlimeJavascriptParserBase$TemplateLiteralParams[" + "in=" + this.__qin_field___qin_in + ", " + "yield=" + this.__qin_field___qin_yield + ", " + "await=" + this.__qin_field___qin_await + ", " + "tagged=" + this.__qin_field_tagged + "]";
  }
}
const SlimeJavascriptParserBase$TemplateLiteralParams = com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams;
com_slime_parser_base_SlimeJavascriptParserBase.__qin_field_RESERVED_WORDS = __QinJavaUtilSet.of("break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "null", "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "await", "yield");
com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT = new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(true, false, false);
com_slime_parser_base_SlimeJavascriptParserBase$StatementParams.__qin_field_DEFAULT = new com_slime_parser_base_SlimeJavascriptParserBase$StatementParams();
com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams.__qin_field_DEFAULT = new com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams();

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_slime_parser_base_SlimeJavascriptParserBase, com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams, com_slime_parser_base_SlimeJavascriptParserBase$StatementParams, com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams, com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams };
