// Generated by Qin JS backend
const shared = { age: 21 };

function run() {
  console.log(shared.age);
  return shared;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  globalThis.__qinResult = __qinResult;
}
