import mitt from "mitt";
import { profile, flags } from "./testqin-module-a.js";
import makePayload from "./testqin-module-fn.js";

console.log(import.meta.url);
import("./testqin-module-a.js");
await 1;
console.log(import("./testqin-module-a.js"));
const dynPath = "./testqin-module-a.js";
console.log(import(dynPath));
const promiseNs = import(dynPath);
const awaitedNs = await promiseNs;
console.log(awaitedNs.profile);
console.log(await import("./testqin-module-a.js"));

const user = { age: 18, name: "qin" };
const stats = { min: 2, max: 8 };
const meta = { tag: "demo", version: 1 };
const opts = { enabled: true, note: null };
console.log(profile.age);
console.log(profile.name);
console.log(flags.ok);
console.log(flags.tag);
console.log(opts.enabled);
console.log(opts.note);
console.log(123);
console.log(user.age);
console.log(user.name);
console.log(stats.min);
console.log(stats.max);
console.log(meta.tag);
console.log(meta.version);
console.log(Math.random());
console.log(Math.abs(user.age));
console.log(Math.floor(3));
console.log(Math.ceil(3));
console.log(Math.round(3));
console.log(Math.trunc(3));
console.log(Math.pow(2, 10));
console.log(Math.sqrt(81));
console.log(Math.sin(0));
console.log(Math.cos(0));
console.log(Math.log(1));
console.log(Math.exp(1));
console.log(Math.max(user.age, stats.max));
console.log(Math.min(user.age, stats.min));
console.log(Number.parseInt("42"));
console.log(Number.parseInt("ff", 16));
console.log(Number.parseFloat("3.14"));
console.log(Number.isFinite(10));
console.log(Number.isInteger(3));
console.log(Number.isSafeInteger(3));
console.log(parseInt("101", 2));
console.log(parseFloat("9.5"));
console.log(isFinite(10));
console.log(isNaN(Number.parseFloat("abc")));
console.log(Object.keys(meta));
console.log(Object.values(meta));
console.log(Object.entries(meta));
console.log(Object.hasOwn(meta, "tag"));
console.log(Date.now());
console.log(JSON.stringify({ ok: 1, text: "hello" }));
console.log(JSON.parse("{\"k\":1}"));
console.log(Math.max(100, 200));
const emitter = mitt();
console.log(emitter);
const payload = makePayload();
console.log(payload);
console.log(payload.code);
console.log(payload.label);
console.log("done");
