import { com_slime_parser_SlimeJavascriptParser, com_slime_parser_SlimeJavascriptParser$SourceType } from "../SlimeJavascriptParser.ts";
import { com_slime_parser_module_SlimeModuleParser } from "../module/SlimeModuleParser.ts";
import { com_slime_parser_class__SlimeClassParser } from "../class_/SlimeClassParser.ts";
import { com_slime_parser_function_SlimeFunctionParser } from "../function/SlimeFunctionParser.ts";
import { com_slime_parser_statements_SlimeStatementParser } from "../statements/SlimeStatementParser.ts";
import { com_slime_parser_expressions_SlimeAssignmentExpressionParser } from "../expressions/SlimeAssignmentExpressionParser.ts";
import { com_slime_parser_expressions_SlimeBinaryExpressionParser } from "../expressions/SlimeBinaryExpressionParser.ts";
import { com_slime_parser_expressions_SlimeUnaryExpressionParser } from "../expressions/SlimeUnaryExpressionParser.ts";
import { com_slime_parser_expressions_SlimePrimaryExpressionParser } from "../expressions/SlimePrimaryExpressionParser.ts";
import { com_slime_parser_literal_SlimeLiteralParser } from "../literal/SlimeLiteralParser.ts";
import { com_slime_parser_identifier_SlimeIdentifierParser } from "../identifier/SlimeIdentifierParser.ts";
import { com_slime_parser_base_SlimeJavascriptParserBase, com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams, com_slime_parser_base_SlimeJavascriptParserBase$StatementParams, com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams, com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams } from "../base/SlimeJavascriptParserBase.ts";
import { com_subhuti_parser_SubhutiParser } from "../../../subhuti/parser/SubhutiParser.ts";
import { com_subhuti_parser_SubhutiParserFinal } from "../../../subhuti/parser/SubhutiParserFinal.ts";
import { com_subhuti_parser_SubhutiParserCombinators, com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher, com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext, com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext, com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame } from "../../../subhuti/parser/SubhutiParserCombinators.ts";
import { com_subhuti_parser_SubhutiParserCore, com_subhuti_parser_SubhutiParserCore$RuleExecutionResult } from "../../../subhuti/parser/SubhutiParserCore.ts";
import { com_subhuti_parser_SubhutiParserState } from "../../../subhuti/parser/SubhutiParserState.ts";
import { com_subhuti_lookahead_SubhutiTokenLookahead } from "../../../subhuti/lookahead/SubhutiTokenLookahead.ts";
const SlimeJavascriptParser = com_slime_parser_SlimeJavascriptParser;
const SourceType = com_slime_parser_SlimeJavascriptParser$SourceType;
const SlimeModuleParser = com_slime_parser_module_SlimeModuleParser;
const SlimeClassParser = com_slime_parser_class__SlimeClassParser;
const SlimeFunctionParser = com_slime_parser_function_SlimeFunctionParser;
const SlimeStatementParser = com_slime_parser_statements_SlimeStatementParser;
const SlimeAssignmentExpressionParser = com_slime_parser_expressions_SlimeAssignmentExpressionParser;
const SlimeBinaryExpressionParser = com_slime_parser_expressions_SlimeBinaryExpressionParser;
const SlimeUnaryExpressionParser = com_slime_parser_expressions_SlimeUnaryExpressionParser;
const SlimePrimaryExpressionParser = com_slime_parser_expressions_SlimePrimaryExpressionParser;
const SlimeLiteralParser = com_slime_parser_literal_SlimeLiteralParser;
const SlimeIdentifierParser = com_slime_parser_identifier_SlimeIdentifierParser;
const SlimeJavascriptParserBase = com_slime_parser_base_SlimeJavascriptParserBase;
const ExpressionParams = com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams;
const StatementParams = com_slime_parser_base_SlimeJavascriptParserBase$StatementParams;
const DeclarationParams = com_slime_parser_base_SlimeJavascriptParserBase$DeclarationParams;
const TemplateLiteralParams = com_slime_parser_base_SlimeJavascriptParserBase$TemplateLiteralParams;
const SubhutiParser = com_subhuti_parser_SubhutiParser;
const SubhutiParserFinal = com_subhuti_parser_SubhutiParserFinal;
const SubhutiParserCombinators = com_subhuti_parser_SubhutiParserCombinators;
const StopTokenMatcher = com_subhuti_parser_SubhutiParserCombinators$StopTokenMatcher;
const AllowErrorOrBranchContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorOrBranchContext;
const AllowErrorContext = com_subhuti_parser_SubhutiParserCombinators$AllowErrorContext;
const ManyTolerantFrame = com_subhuti_parser_SubhutiParserCombinators$ManyTolerantFrame;
const SubhutiParserCore = com_subhuti_parser_SubhutiParserCore;
const RuleExecutionResult = com_subhuti_parser_SubhutiParserCore$RuleExecutionResult;
const SubhutiParserState = com_subhuti_parser_SubhutiParserState;

// Generated by Qin TypeScript backend
import { __qin_builtin_constructor__, __qin_java_pattern_regexp__, __QinJavaLangString, __qin_java_functional, __qin_java_class_info__, __qin_binary__, __qin_logical__ } from "@qin/java-sdk-js";
import { __qin_subhuti_rule_cache_key } from "@qin/java-sdk-js/tooling";

function __qin_structural_object__(value) {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return false;
  return value.constructor == null || value.constructor === Object;
}
class com_slime_parser_typescript_SlimeTSTypeParser extends com_slime_parser_SlimeJavascriptParser {
  constructor(...__qin_args: any[]) {
    switch (__qin_args.length) {
      case 1: {
        const sourceCode: any = __qin_args[0];
        super(sourceCode);
        this.__qin_constructor_com_slime_parser_typescript_SlimeTSTypeParser_1(sourceCode);
        return;
      }
      default: throw new Error("Unsupported Java constructor arity: SlimeTSTypeParser/" + __qin_args.length);
    }
  }
  __qin_constructor_com_slime_parser_typescript_SlimeTSTypeParser_1(sourceCode: string): void {
    null;
  }
  TSTypeAnnotation(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeAnnotation();
    }), "TSTypeAnnotation", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeAnnotation(): any {
    this.__qin_field_tokenConsumer.Colon();
    this.TSType();
    return null;
  }
  TSType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSType();
    }), "TSType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSType(): any {
    this.Or(__qin_java_functional(() => {
      return this.TSTypePredicate();
    }), __qin_java_functional(() => {
      return this.TSFunctionType();
    }), __qin_java_functional(() => {
      return this.TSConstructorType();
    }), __qin_java_functional(() => {
      return this.TSConditionalType();
    }));
    return null;
  }
  TSKeywordType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSKeywordType();
    }), "TSKeywordType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSKeywordType(): any {
    this.Or(__qin_java_functional(() => {
      return this.TSNumberKeyword();
    }), __qin_java_functional(() => {
      return this.TSStringKeyword();
    }), __qin_java_functional(() => {
      return this.TSBooleanKeyword();
    }), __qin_java_functional(() => {
      return this.TSAnyKeyword();
    }), __qin_java_functional(() => {
      return this.TSUnknownKeyword();
    }), __qin_java_functional(() => {
      return this.TSVoidKeyword();
    }), __qin_java_functional(() => {
      return this.TSNeverKeyword();
    }), __qin_java_functional(() => {
      return this.TSNullKeyword();
    }), __qin_java_functional(() => {
      return this.TSUndefinedKeyword();
    }), __qin_java_functional(() => {
      return this.TSObjectKeyword();
    }), __qin_java_functional(() => {
      return this.TSSymbolKeyword();
    }), __qin_java_functional(() => {
      return this.TSBigIntKeyword();
    }));
    return null;
  }
  TSNumberKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSNumberKeyword();
    }), "TSNumberKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSNumberKeyword(): any {
    this.consumeIdentifierValue("number");
    return null;
  }
  TSStringKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSStringKeyword();
    }), "TSStringKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSStringKeyword(): any {
    this.consumeIdentifierValue("string");
    return null;
  }
  TSBooleanKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSBooleanKeyword();
    }), "TSBooleanKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSBooleanKeyword(): any {
    this.consumeIdentifierValue("boolean");
    return null;
  }
  TSAnyKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSAnyKeyword();
    }), "TSAnyKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSAnyKeyword(): any {
    this.consumeIdentifierValue("any");
    return null;
  }
  TSUnknownKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSUnknownKeyword();
    }), "TSUnknownKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSUnknownKeyword(): any {
    this.consumeIdentifierValue("unknown");
    return null;
  }
  TSVoidKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSVoidKeyword();
    }), "TSVoidKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSVoidKeyword(): any {
    this.__qin_field_tokenConsumer.Void();
    return null;
  }
  TSNeverKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSNeverKeyword();
    }), "TSNeverKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSNeverKeyword(): any {
    this.consumeIdentifierValue("never");
    return null;
  }
  TSNullKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSNullKeyword();
    }), "TSNullKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSNullKeyword(): any {
    this.__qin_field_tokenConsumer.NullLiteral();
    return null;
  }
  TSUndefinedKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSUndefinedKeyword();
    }), "TSUndefinedKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSUndefinedKeyword(): any {
    this.consumeIdentifierValue("undefined");
    return null;
  }
  TSObjectKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSObjectKeyword();
    }), "TSObjectKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSObjectKeyword(): any {
    this.consumeIdentifierValue("object");
    return null;
  }
  TSSymbolKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSSymbolKeyword();
    }), "TSSymbolKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSSymbolKeyword(): any {
    this.consumeIdentifierValue("symbol");
    return null;
  }
  TSBigIntKeyword(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSBigIntKeyword();
    }), "TSBigIntKeyword", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSBigIntKeyword(): any {
    this.consumeIdentifierValue("bigint");
    return null;
  }
  TSThisType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSThisType();
    }), "TSThisType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSThisType(): any {
    this.__qin_field_tokenConsumer.This();
    return null;
  }
  TSUnionOrIntersectionType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSUnionOrIntersectionType();
    }), "TSUnionOrIntersectionType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSUnionOrIntersectionType(): any {
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.BitwiseOr();
    }));
    this.TSIntersectionType();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.BitwiseOr();
      this.TSIntersectionType();
      return null;
    }));
    return null;
  }
  TSIntersectionType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSIntersectionType();
    }), "TSIntersectionType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSIntersectionType(): any {
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.BitwiseAnd();
    }));
    this.TSTypeOperand();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.BitwiseAnd();
      this.TSTypeOperand();
      return null;
    }));
    return null;
  }
  TSPrimaryType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSPrimaryType();
    }), "TSPrimaryType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSPrimaryType(): any {
    this.Or(__qin_java_functional(() => {
      return this.TSMappedType();
    }), __qin_java_functional(() => {
      return this.TSTypeLiteral();
    }), __qin_java_functional(() => {
      return this.TSTupleType();
    }), __qin_java_functional(() => {
      return this.TSThisType();
    }), __qin_java_functional(() => {
      return this.TSKeywordType();
    }), __qin_java_functional(() => {
      return this.TSLiteralType();
    }), __qin_java_functional(() => {
      return this.TSTypeReference();
    }), __qin_java_functional(() => {
      return this.TSParenthesizedType();
    }));
    return null;
  }
  TSTypeReference(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeReference();
    }), "TSTypeReference", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeReference(): any {
    this.TSTypeName();
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterInstantiation();
    }));
    return null;
  }
  TSTypeName(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeName();
    }), "TSTypeName", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeName(): any {
    this.Identifier();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Dot();
      this.Identifier();
      return null;
    }));
    return null;
  }
  TSTypeParameterInstantiation(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeParameterInstantiation();
    }), "TSTypeParameterInstantiation", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeParameterInstantiation(): any {
    this.__qin_field_tokenConsumer.Less();
    this.TSType();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Comma();
      this.TSType();
      return null;
    }));
    this.consumeGreaterInTypeContext();
    return null;
  }
  consumeGreaterInTypeContext(): any {
    if (this.isParserFail()) {
      return null;
    }
    let token: any = this.LA(1.0);
    if (__qin_binary__("==", token, null)) {
      this.setParseFail();
      return null;
    }
    return null;
  }
  TSTypeLiteral(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeLiteral();
    }), "TSTypeLiteral", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeLiteral(): any {
    this.__qin_field_tokenConsumer.LBrace();
    this.Option(__qin_java_functional(() => {
      this.TSTypeMember();
      this.Many(__qin_java_functional(() => {
      this.Option(__qin_java_functional(() => {
      return this.Or(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Semicolon();
    }), __qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Comma();
    }));
    }));
      if ((() => {
      if (__qin_binary__("!=", this.LA(1.0), null)) {
        return (() => {
      if (__QinJavaLangString.equals("RBrace", this.LA(1.0).getTokenName())) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })()) {
        this.TSTypeMember();
      }
      return null;
    }));
      return null;
    }));
    this.__qin_field_tokenConsumer.RBrace();
    return null;
  }
  TSTypeMembers(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeMembers();
    }), "TSTypeMembers", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeMembers(): any {
    this.TSTypeMember();
    this.Many(__qin_java_functional(() => {
      this.Or(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Semicolon();
    }), __qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Comma();
    }));
      this.Option(__qin_java_functional(() => {
      return this.TSTypeMember();
    }));
      return null;
    }));
    return null;
  }
  TSTypeMember(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeMember();
    }), "TSTypeMember", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeMember(): any {
    this.Or(__qin_java_functional(() => {
      return this.TSIndexSignature();
    }), __qin_java_functional(() => {
      return this.TSCallSignatureDeclaration();
    }), __qin_java_functional(() => {
      return this.TSConstructSignatureDeclaration();
    }), __qin_java_functional(() => {
      return this.TSPropertyOrMethodSignature();
    }));
    return null;
  }
  TSPropertyOrMethodSignature(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSPropertyOrMethodSignature();
    }), "TSPropertyOrMethodSignature", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSPropertyOrMethodSignature(): any {
    let isReadonlyModifier: any = (() => {
      if (this.isContextual("readonly")) {
        return (() => {
      if (this.lookaheadIn(["Colon", "Question"], 2.0)) {
        return false;
      }
      return true;
    })();
      }
      return false;
    })();
    if (isReadonlyModifier) {
      this.consumeIdentifierValue("readonly");
    }
    this.PropertyName(com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT);
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
    this.Or(__qin_java_functional(() => {
      this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterDeclaration();
    }));
      this.__qin_field_tokenConsumer.LParen();
      this.Option(__qin_java_functional(() => {
      return this.TSParameterList();
    }));
      this.__qin_field_tokenConsumer.RParen();
      this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
      return null;
    }), __qin_java_functional(() => {
      return this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
    }));
    return null;
  }
  TSPropertySignature(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSPropertySignature();
    }), "TSPropertySignature", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSPropertySignature(): any {
    this.Option(__qin_java_functional(() => {
      return this.consumeIdentifierValue("readonly");
    }));
    this.PropertyName(com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT);
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
    this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
    return null;
  }
  TSMethodSignature(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSMethodSignature();
    }), "TSMethodSignature", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSMethodSignature(): any {
    this.PropertyName(com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT);
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterDeclaration();
    }));
    this.__qin_field_tokenConsumer.LParen();
    this.Option(__qin_java_functional(() => {
      return this.TSParameterList();
    }));
    this.__qin_field_tokenConsumer.RParen();
    this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
    return null;
  }
  TSCallSignatureDeclaration(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSCallSignatureDeclaration();
    }), "TSCallSignatureDeclaration", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSCallSignatureDeclaration(): any {
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterDeclaration();
    }));
    this.__qin_field_tokenConsumer.LParen();
    this.Option(__qin_java_functional(() => {
      return this.TSParameterList();
    }));
    this.__qin_field_tokenConsumer.RParen();
    this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
    return null;
  }
  TSConstructSignatureDeclaration(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSConstructSignatureDeclaration();
    }), "TSConstructSignatureDeclaration", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSConstructSignatureDeclaration(): any {
    this.__qin_field_tokenConsumer.New();
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterDeclaration();
    }));
    this.__qin_field_tokenConsumer.LParen();
    this.Option(__qin_java_functional(() => {
      return this.TSParameterList();
    }));
    this.__qin_field_tokenConsumer.RParen();
    this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
    return null;
  }
  TSIndexSignature(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSIndexSignature();
    }), "TSIndexSignature", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSIndexSignature(): any {
    this.Option(__qin_java_functional(() => {
      return this.consumeIdentifierValue("readonly");
    }));
    this.__qin_field_tokenConsumer.LBracket();
    this.Identifier();
    this.__qin_field_tokenConsumer.Colon();
    this.TSType();
    this.__qin_field_tokenConsumer.RBracket();
    this.__qin_field_tokenConsumer.Colon();
    this.TSType();
    return null;
  }
  TSNonArrayType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSNonArrayType();
    }), "TSNonArrayType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSNonArrayType(): any {
    this.TSPrefixTypeOrPrimary();
    return null;
  }
  TSArrayType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSArrayType();
    }), "TSArrayType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSArrayType(): any {
    this.TSNonArrayType();
    this.__qin_field_tokenConsumer.LBracket();
    this.__qin_field_tokenConsumer.RBracket();
    return null;
  }
  TSTupleType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTupleType();
    }), "TSTupleType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTupleType(): any {
    this.__qin_field_tokenConsumer.LBracket();
    this.Option(__qin_java_functional(() => {
      this.TSTupleElementType();
      this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Comma();
      this.TSTupleElementType();
      return null;
    }));
      return null;
    }));
    this.__qin_field_tokenConsumer.RBracket();
    return null;
  }
  TSTupleElementType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTupleElementType();
    }), "TSTupleElementType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTupleElementType(): any {
    this.Or(__qin_java_functional(() => {
      return this.TSRestType();
    }), __qin_java_functional(() => {
      return this.TSNamedTupleMember();
    }), __qin_java_functional(() => {
      this.TSType();
      this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
      return null;
    }));
    return null;
  }
  TSNamedTupleMember(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSNamedTupleMember();
    }), "TSNamedTupleMember", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSNamedTupleMember(): any {
    this.Identifier();
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
    this.__qin_field_tokenConsumer.Colon();
    this.TSType();
    return null;
  }
  TSFunctionType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSFunctionType();
    }), "TSFunctionType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSFunctionType(): any {
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterDeclaration();
    }));
    this.__qin_field_tokenConsumer.LParen();
    this.Option(__qin_java_functional(() => {
      return this.TSParameterList();
    }));
    this.__qin_field_tokenConsumer.RParen();
    this.__qin_field_tokenConsumer.Arrow();
    this.TSType();
    return null;
  }
  TSConstructorType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSConstructorType();
    }), "TSConstructorType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSConstructorType(): any {
    this.Option(__qin_java_functional(() => {
      return this.consumeIdentifierValue("abstract");
    }));
    this.__qin_field_tokenConsumer.New();
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterDeclaration();
    }));
    this.__qin_field_tokenConsumer.LParen();
    this.Option(__qin_java_functional(() => {
      return this.TSParameterList();
    }));
    this.__qin_field_tokenConsumer.RParen();
    this.__qin_field_tokenConsumer.Arrow();
    this.TSType();
    return null;
  }
  TSParameterList(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSParameterList();
    }), "TSParameterList", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSParameterList(): any {
    this.TSParameter();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Comma();
      this.TSParameter();
      return null;
    }));
    return null;
  }
  TSParameter(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSParameter();
    }), "TSParameter", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSParameter(): any {
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Ellipsis();
      this.BindingIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(false, false, false));
      this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
      return null;
    }), __qin_java_functional(() => {
      this.Option(__qin_java_functional(() => {
      return this.Or(__qin_java_functional(() => {
      return this.consumeIdentifierValue("public");
    }), __qin_java_functional(() => {
      return this.consumeIdentifierValue("private");
    }), __qin_java_functional(() => {
      return this.consumeIdentifierValue("protected");
    }), __qin_java_functional(() => {
      return this.consumeIdentifierValue("readonly");
    }));
    }));
      this.Or(__qin_java_functional(() => {
      return this.BindingIdentifier(new com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams(false, false, false));
    }), __qin_java_functional(() => {
      return this.BindingPattern(com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT);
    }));
      this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
      this.Option(__qin_java_functional(() => {
      return this.TSTypeAnnotation();
    }));
      this.Option(__qin_java_functional(() => {
      return this.Initializer(com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT);
    }));
      return null;
    }));
    return null;
  }
  TSTypeQuery(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeQuery();
    }), "TSTypeQuery", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeQuery(): any {
    this.__qin_field_tokenConsumer.Typeof();
    this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.This();
      this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Dot();
      this.Identifier();
      return null;
    }));
      return null;
    }), __qin_java_functional(() => {
      return this.TSTypeName();
    }), __qin_java_functional(() => {
      this.ImportCall(com_slime_parser_base_SlimeJavascriptParserBase$ExpressionParams.__qin_field_DEFAULT);
      this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Dot();
      this.Identifier();
      return null;
    }));
      return null;
    }));
    this.Option(__qin_java_functional(() => {
      return this.TSTypeParameterInstantiation();
    }));
    return null;
  }
  TSIndexedAccessType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSIndexedAccessType();
    }), "TSIndexedAccessType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSIndexedAccessType(): any {
    this.__qin_field_tokenConsumer.LBracket();
    this.TSType();
    this.__qin_field_tokenConsumer.RBracket();
    return null;
  }
  TSParenthesizedType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSParenthesizedType();
    }), "TSParenthesizedType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSParenthesizedType(): any {
    this.__qin_field_tokenConsumer.LParen();
    this.TSType();
    this.__qin_field_tokenConsumer.RParen();
    return null;
  }
  TSConditionalType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSConditionalType();
    }), "TSConditionalType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSConditionalType(): any {
    this.TSUnionOrIntersectionType();
    this.Option(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Extends();
      this.TSUnionOrIntersectionType();
      this.__qin_field_tokenConsumer.Question();
      this.TSType();
      this.__qin_field_tokenConsumer.Colon();
      this.TSType();
      return null;
    }));
    return null;
  }
  TSLiteralType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSLiteralType();
    }), "TSLiteralType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSLiteralType(): any {
    this.Or(__qin_java_functional(() => {
      return this.NumericLiteral();
    }), __qin_java_functional(() => {
      return this.StringLiteral();
    }), __qin_java_functional(() => {
      return this.BooleanLiteral();
    }), __qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.NullLiteral();
    }));
    return null;
  }
  TSTemplateLiteralType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTemplateLiteralType();
    }), "TSTemplateLiteralType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTemplateLiteralType(): any {
    this.TemplateLiteral();
    return null;
  }
  TSTypeParameterDeclaration(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeParameterDeclaration();
    }), "TSTypeParameterDeclaration", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeParameterDeclaration(): any {
    this.__qin_field_tokenConsumer.Less();
    this.TSTypeParameter();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Comma();
      this.TSTypeParameter();
      return null;
    }));
    this.__qin_field_tokenConsumer.Greater();
    return null;
  }
  TSTypeParameter(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeParameter();
    }), "TSTypeParameter", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeParameter(): any {
    this.Identifier();
    this.Option(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Extends();
      this.TSType();
      return null;
    }));
    this.Option(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Assign();
      this.TSType();
      return null;
    }));
    return null;
  }
  TSTypeOperand(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeOperand();
    }), "TSTypeOperand", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeOperand(): any {
    this.TSPrefixTypeOrPrimary();
    this.Many(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.LBracket();
      this.Option(__qin_java_functional(() => {
      return this.TSType();
    }));
      this.__qin_field_tokenConsumer.RBracket();
      return null;
    }));
    return null;
  }
  TSPrefixTypeOrPrimary(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSPrefixTypeOrPrimary();
    }), "TSPrefixTypeOrPrimary", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSPrefixTypeOrPrimary(): any {
    this.Or(__qin_java_functional(() => {
      return this.TSTypeQuery();
    }), __qin_java_functional(() => {
      return this.TSTypeOperator();
    }), __qin_java_functional(() => {
      return this.TSInferType();
    }), __qin_java_functional(() => {
      return this.TSPrimaryType();
    }));
    return null;
  }
  TSTypeOperator(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypeOperator();
    }), "TSTypeOperator", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypeOperator(): any {
    this.Or(__qin_java_functional(() => {
      this.consumeIdentifierValue("keyof");
      this.TSTypeOperand();
      return null;
    }), __qin_java_functional(() => {
      this.consumeIdentifierValue("readonly");
      this.TSTypeOperand();
      return null;
    }), __qin_java_functional(() => {
      this.consumeIdentifierValue("unique");
      this.consumeIdentifierValue("symbol");
      return null;
    }));
    return null;
  }
  TSInferType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSInferType();
    }), "TSInferType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSInferType(): any {
    this.consumeIdentifierValue("infer");
    this.Identifier();
    this.Option(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Extends();
      this.TSType();
      return null;
    }));
    return null;
  }
  TSRestType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSRestType();
    }), "TSRestType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSRestType(): any {
    this.__qin_field_tokenConsumer.Ellipsis();
    this.TSType();
    return null;
  }
  TSTypePredicate(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSTypePredicate();
    }), "TSTypePredicate", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSTypePredicate(): any {
    this.Or(__qin_java_functional(() => {
      this.consumeIdentifierValue("asserts");
      this.Or(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.This();
    }), __qin_java_functional(() => {
      return this.Identifier();
    }));
      this.Option(__qin_java_functional(() => {
      this.consumeIdentifierValue("is");
      this.TSType();
      return null;
    }));
      return null;
    }), __qin_java_functional(() => {
      this.Or(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.This();
    }), __qin_java_functional(() => {
      return this.Identifier();
    }));
      this.consumeIdentifierValue("is");
      this.TSType();
      return null;
    }));
    return null;
  }
  TSMappedType(): any {
    return this.executeRuleWrapper(__qin_java_functional(() => {
      return this.__qin_subhuti_raw_TSMappedType();
    }), "TSMappedType", "SlimeTSTypeParser", __qin_subhuti_rule_cache_key([]));
  }
  __qin_subhuti_raw_TSMappedType(): any {
    this.__qin_field_tokenConsumer.LBrace();
    this.Option(__qin_java_functional(() => {
      this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Plus();
      this.consumeIdentifierValue("readonly");
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Minus();
      this.consumeIdentifierValue("readonly");
      return null;
    }), __qin_java_functional(() => {
      return this.consumeIdentifierValue("readonly");
    }));
      return null;
    }));
    this.__qin_field_tokenConsumer.LBracket();
    this.Identifier();
    this.__qin_field_tokenConsumer.In();
    this.TSType();
    this.Option(__qin_java_functional(() => {
      this.consumeIdentifierValue("as");
      this.TSType();
      return null;
    }));
    this.__qin_field_tokenConsumer.RBracket();
    this.Option(__qin_java_functional(() => {
      this.Or(__qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Plus();
      this.__qin_field_tokenConsumer.Question();
      return null;
    }), __qin_java_functional(() => {
      this.__qin_field_tokenConsumer.Minus();
      this.__qin_field_tokenConsumer.Question();
      return null;
    }), __qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Question();
    }));
      return null;
    }));
    this.__qin_field_tokenConsumer.Colon();
    this.TSType();
    this.Option(__qin_java_functional(() => {
      return this.__qin_field_tokenConsumer.Semicolon();
    }));
    this.__qin_field_tokenConsumer.RBrace();
    return null;
  }
}
const SlimeTSTypeParser = com_slime_parser_typescript_SlimeTSTypeParser;

function run() {
  return null;
}

const __qinResult = run();
if (typeof globalThis !== 'undefined') {
  const __qinGlobal = globalThis as any;
  __qinGlobal.__qinResult = __qinResult;
}

export { com_slime_parser_typescript_SlimeTSTypeParser };
